#pragma once

#define POKEMON_NAME_LENGTH 10

#define SPECIES_NONE 0x0
#define SPECIES_BULBORBLARVA 0x1
#define SPECIES_BULBORB 0x2
#define SPECIES_JUMBOBULBORB 0x3
#define SPECIES_FIERYBLOWLET 0x4
#define SPECIES_FIERYBLOWHOG 0x5
#define SPECIES_TITANBLOWHOG 0x6
#define SPECIES_WOLPOLE 0x7
#define SPECIES_YELLOWWOLLYHOP 0x8
#define SPECIES_MASTERHOP 0x9
#define SPECIES_FLINTBEETLE 0xA
#define SPECIES_DOODLEBUG 0xB
#define SPECIES_GLINTBEETLE 0xC
#define SPECIES_SWOOPINGSNITCHBUG 0xD
#define SPECIES_BUMBLINGSNITCHBUG 0xE
#define SPECIES_DIRIGIBUG 0xF
#define SPECIES_SNOWBULBORB 0x10
#define SPECIES_DWARFFROSTYBULBORB 0x11
#define SPECIES_FROSTYBULBORB 0x12
#define SPECIES_CRUMBUG 0x13
#define SPECIES_BREADBUG 0x14
#define SPECIES_GIANTBREADBUG 0x15
#define SPECIES_EMPERORBULBLAX 0x16 
#define SPECIES_SOVREIGNBULBLAX 0x17 
#define SPECIES_DWARFBULBEAR 0x18
#define SPECIES_SPOTTYBULBEAR 0x19
#define SPECIES_HONEYWISP 0x1A
#define SPECIES_DANDELFLY 0x1B
#define SPECIES_DOWNYSNAGRET 0x1C
#define SPECIES_BURROWINGSNAGRET 0x1D
#define SPECIES_PILEATEDSNAGRET 0x1E
#define SPECIES_FEMALESHEARGRUB 0x1F
#define SPECIES_SWARMINGSHEARGRUB 0x20
#define SPECIES_MAMASHEARGRUB 0x21
#define SPECIES_MALESHEARGRUB 0x22
#define SPECIES_SHEARWIG 0x23
#define SPECIES_QUEENSHEARWIG 0x24
#define SPECIES_ARISTOCRABOFFSPRING 0x25
#define SPECIES_ARISTOCRAB 0x26
#define SPECIES_GOOLIX 0x27
#define SPECIES_FOOLIX 0x28
#define SPECIES_ARCTICCANNONLARVA 0x29
#define SPECIES_ARCTICCANNONBEETLE 0x2A
#define SPECIES_SKITTERLEAF 0x2B
#define SPECIES_DESICCATEDSKITTERLEAF 0x2C
#define SPECIES_ARMOREDCANNONLARVA 0x2D
#define SPECIES_ARMOREDCANNONBEETLE 0x2E
#define SPECIES_HORNEDCANNONBEETLE 0x2F
#define SPECIES_CREEPINGCHRYSANTHEMUM 0x30
#define SPECIES_STARTLESPORE 0x31
#define SPECIES_HERMITCRAWMAD 0x32
#define SPECIES_BUGEYEDCRAWMAD 0x33
#define SPECIES_DWARFBULBORB 0x34
#define SPECIES_DWARFORANGEBULBORB 0x35
#define SPECIES_BEADYLONGLEGS 0x36
#define SPECIES_RAGINGLONGLEGS 0x37
#define SPECIES_BALDYLONGLEGS 0x38
#define SPECIES_SHAGGYLONGLEGS 0x39
#define SPECIES_BULBMIN 0x3A
#define SPECIES_ADULTBULBMIN 0x3B
#define SPECIES_SCORNET 0x3C
#define SPECIES_SCORNETMAESTRO 0x3D 
#define SPECIES_BURROWNIT 0x3E
#define SPECIES_JOUSTMITE 0x3F 
#define SPECIES_FLIGHTYJOUSTMITE 0x40 
#define SPECIES_VOLATILEDWEEVIL 0x41
#define SPECIES_MANATLEGS 0x42
#define SPECIES_SKUTTERCHUCK 0x43 
#define SPECIES_CALCIFIEDCRUSHBLAT 0x44 
#define SPECIES_ARACHNODE 0x45
#define SPECIES_MOLDYDWARFBULBORB 0x46
#define SPECIES_MOLDYSLOOCH 0x47
#define SPECIES_TOXSTOOL 0x48
#define SPECIES_PHOSBAT 0x49
#define SPECIES_VEHEAMOTHPHOSBAT 0x4A
#define SPECIES_PUCKERINGBLINNOW 0x4B
#define SPECIES_SPUTTLEFISH 0x4C
#define SPECIES_PRICKLEPUFF 0x4D
#define SPECIES_UJADANI 0x4E 
#define SPECIES_MITITE 0x4F 
#define SPECIES_WITHERINGBLOWHOG 0x50 
#define SPECIES_PUFFYBLOWHOG 0x51
#define SPECIES_MINIATURESNOOTWHACKER 0x52 
#define SPECIES_MAMMOTHSNOOTWHACKER 0x53 
#define SPECIES_PYROCLASTICSLOOCH 0x54
#define SPECIES_LESSERSPOTTEDJELLYFLOAT 0x55
#define SPECIES_GREATERSPOTTEDJELLYFLOAT 0x56
#define SPECIES_TOADYBLOYSTER 0x57 
#define SPECIES_RANGINGBLOYSTER 0x58 
#define SPECIES_SNOWYBLOWHOG 0x59
#define SPECIES_BLIZZARDINGBLOWHOG 0x5A
#define SPECIES_GILDEMANDWEE 0x5B 
#define SPECIES_GILDEMANDER 0x5C 
#define SPECIES_WADDLEQUAFF 0x5D 
#define SPECIES_GRUBCHUCKER 0x5E 
#define SPECIES_PEARLYCLAMCLAMP 0x5F 
#define SPECIES_SUNQUISH 0x60
#define SPECIES_PROQUILLION 0x61
#define SPECIES_TUSKEDBLOWHOG 0x62 
#define SPECIES_SNOWFLAKEFLUTTERTAIL 0x63
#define SPECIES_BOGSWALLOW 0x64
#define SPECIES_PUFFMIN 0x65
#define SPECIES_WOLLYHOP 0x66
#define SPECIES_CHILLYHOP 0x67 
#define SPECIES_BLOOMCAPBLOYSTER 0x68 
#define SPECIES_SCORCHCAKE 0x69
#define SPECIES_WATERDUMPLE 0x6A
#define SPECIES_LONGWATERDUMPLE 0x6B
#define SPECIES_MOCKIWI 0x6C
#define SPECIES_CRESTEDMOCKIWI 0x6D 
#define SPECIES_ELONGATEDCRUSHBLAT 0x6E 
#define SPECIES_PUFFSTALK 0x6F 
#define SPECIES_PUFFSTOOL 0x70 
#define SPECIES_ANODEBEETLE 0x71 
#define SPECIES_EMPRESSBULBLAX 0x72 
#define SPECIES_SKEETERSKATE 0x73 
#define SPECIES_MUCKERSKATE 0x74 
#define SPECIES_GROOVYLONGLEGS 0x75 
#define SPECIES_CRUSTEDRUMPUP 0x76 
#define SPECIES_BEARDEDAMPRAT 0x77
#define SPECIES_FIERYBULBLAX 0x78 
#define SPECIES_GATTLINGGROINK 0x79
#define SPECIES_ARMURK 0x7A 
#define SPECIES_SEGMENTEDCRAWBSTER 0x7B 
#define SPECIES_ARMOREDMAWDAD 0x7C
#define SPECIES_SANDBELCHINGMEERSLUG 0x7D 
#define SPECIES_CLICKINGSLURKER 0x7E 
#define SPECIES_LURINGSLURKER 0x7F 
#define SPECIES_MEDUSALSLURKER 0x80 
#define SPECIES_PELLETPOSY 0x81
#define SPECIES_MASTERONION 0x82
#define SPECIES_OATCHI 0x83
#define SPECIES_QUAGGLEDMIRECLOPS 0x84
#define SPECIES_ALBINODWARFBULBORB 0x85
#define SPECIES_HAIRYBULBORB 0x86
#define SPECIES_WHIPTONGUEBULBORB 0x87
#define SPECIES_ORANGEBULBORB 0x88
#define SPECIES_WHITEPIKMIN 0x89
#define SPECIES_BLUEPIKMIN 0x8A
#define SPECIES_ROCKPIKMIN 0x8B
#define SPECIES_YELLOWPIKMIN 0x8C
#define SPECIES_WINGEDPIKMIN 0x8D
#define SPECIES_REDPIKMIN 0x8E
#define SPECIES_PURPLEPIKMIN 0x8F
#define SPECIES_WATERWRAITH 0x90
#define SPECIES_TITANDWEEVIL 0x91
#define SPECIES_PLASMWRAITH 0x92
#define SPECIES_ICEPIKMIN 0x93
#define SPECIES_GLOWSEED 0x94
#define SPECIES_GLOWPIKMIN 0x95
#define SPECIES_SMOKYPROGG 0x96
#define SPECIES_MAMUTA 0x97
#define SPECIES_MOSS 0x98
#define SPECIES_TOYBORB 0x99
#define SPECIES_BULBLORD 0x9A
#define SPECIES_PINCHIPEDE 0x9B
#define SPECIES_LARGEMOUTHWOLLYHOP 0x9C
#define SPECIES_TOYBLOWHOG 0x9D
#define SPECIES_TELESCOPINGPUMPHOG 0x9E
#define SPECIES_BEEB 0x9F
#define SPECIES_BLADEDBEEB 0xA0
#define SPECIES_STUDDEDBEEB 0xA1
#define SPECIES_FIREFLAPBULBORB 0xA2
#define SPECIES_ICEBLOWNDWEEVIL 0xA3
#define SPECIES_SPECTRALID 0xA4
#define SPECIES_BLUBBUG 0xA5
#define SPECIES_PUFFYBLUBBUG 0xA6
#define SPECIES_STUFFEDBELLBLOOM 0xA7
#define SPECIES_CENTIPARE 0xA8
#define SPECIES_ADULTCENTIPARE 0xA9
#define SPECIES_WATERYBLOWHOG 0xAA
#define SPECIES_GRABBIT 0xAB
#define SPECIES_COPPELLER 0xAC
#define SPECIES_MUGGONFLY 0xAD
#define SPECIES_ELECTRICCOTTONADE 0xAE
#define SPECIES_WADDLEPUS 0xAF
#define SPECIES_CRAMMEDWRAITH 0xB0
#define SPECIES_BERSERKLEECHHYDROE 0xB1
#define SPECIES_PEBBLEPITCHER 0xB2
#define SPECIES_ANCIENTSIREHOUND 0xB3
#define SPECIES_COURAGEREACTOR 0xB4
#define SPECIES_ASSEMBLEDCOURAGE 0xB5
#define SPECIES_REMEMBEREDOLDBUDDY 0xB6
#define SPECIES_BULBORBWITHAGUN 0xB7
#define SPECIES_KIRBY 0xB8
#define SPECIES_SOUL 0xB9
#define SPECIES_PLACEHOLDERLARVA 0xBA
#define SPECIES_DEMO77 0xBB
#define SPECIES_USUBA 0xBC
#define SPECIES_KAKUREIMO 0xBD
#define SPECIES_PIKUTABE 0xBE
#define SPECIES_NAMAPONGASHI 0xBF
#define SPECIES_CHAPPYPROTO 0xC0

#define SPECIES_EGG 0xC1

#define SPECIES_GILDEMANDWEE_NOGOLD 0xC2	//091
#define SPECIES_GILDEMANDER_NOGOLD 0xC3		//092

#define SPECIES_REDBUBBLIMP 0xC4
#define SPECIES_STARNACLE 0xC5
#define SPECIES_SHEARFLEA 0xC6
#define SPECIES_WHISKERPILLAR 0xC7
#define SPECIES_ICYBLOWHOG 0xC8

#define SPECIES_FREEZECAKE 0xC9
#define SPECIES_SHOCKCAKE 0xCA
#define SPECIES_WIDEMOUTHEDANODEBEETLE 0xCB
#define SPECIES_DECORATEDCANNONBEETLE 0xCC
#define SPECIES_ANTENNABEETLE 0xCD

#define SPECIES_BEARDEDAMPRAT_STATIC 0xCE	//119
#define SPECIES_REDPIKMIN_VETERAN 0xCF		//142
#define SPECIES_TITANDWEEVIL_ELECTRIC 0xD0	//145
#define SPECIES_TITANDWEEVIL_FIRE 0xD1		//145
#define SPECIES_TITANDWEEVIL_POISON 0xD2	//145
#define SPECIES_TITANDWEEVIL_WATER 0xD3		//145
#define SPECIES_SMOKYPROGG_MASTER 0xD4		//150
#define SPECIES_SPECTRALID_RED 0xD5		//164
#define SPECIES_SPECTRALID_YELLOW 0xD6		//164
#define SPECIES_SPECTRALID_UNMARKED 0xD7	//164
#define SPECIES_SPECTRALID_UNMARKEDRED 0xD8	//164
#define SPECIES_SPECTRALID_UNMARKEDPURPLE 0xD9	//164
#define SPECIES_SPECTRALID_ELECTRIC 0xDA	//164
#define SPECIES_SPECTRALID_HEY0 0xDB		//164
#define SPECIES_SPECTRALID_HEY1 0xDC		//164
#define SPECIES_ANCIENTSIREHOUND_ICE 0xDD	//179
#define SPECIES_ANCIENTSIREHOUND_ELECTRIC 0xDE	//179
#define SPECIES_ANCIENTSIREHOUND_FIRE 0xDF	//179
#define SPECIES_ANCIENTSIREHOUND_GLOOM 0xE0	//179
#define SPECIES_KIRBY_FLYING 0xE1		//184
#define SPECIES_KIRBY_GRASS 0xE2		//184
#define SPECIES_KIRBY_BUG 0xE3			//184
#define SPECIES_KIRBY_POISON 0xE4		//184
#define SPECIES_KIRBY_WATER 0xE5		//184
#define SPECIES_KIRBY_ICE 0xE6			//184
#define SPECIES_KIRBY_FIRE 0xE7			//184
#define SPECIES_KIRBY_ELECTRIC 0xE8		//184
#define SPECIES_KIRBY_FIGHTING 0xE9		//184
#define SPECIES_KIRBY_ROCK 0xEA			//184
#define SPECIES_KIRBY_GROUND 0xEB		//184
#define SPECIES_KIRBY_PSYCHIC 0xEC		//184
#define SPECIES_KIRBY_GHOST 0xED		//184
#define SPECIES_KIRBY_DRAGON 0xEE		//184
#define SPECIES_KIRBY_DARK 0xEF			//184
#define SPECIES_KIRBY_STEEL 0xF0		//184
#define SPECIES_KIRBY_FAIRY 0xF1		//184
#define SPECIES_SOUL_RED 0xF2			//185
#define SPECIES_SOUL_YELLOW 0xF3		//185
#define SPECIES_SOUL_BLUE 0xF4			//185
#define SPECIES_SOUL_PURPLE 0xF5		//185
#define SPECIES_SOUL_WHITE 0xF6			//185
#define SPECIES_SOUL_ROCK 0xF7			//185
#define SPECIES_SOUL_WINGED 0xF8		//185
#define SPECIES_SOUL_ICE 0xF9			//185

#define SPECIES_WATERWRAITH_NOTIRES 0xFA

#define SPECIES_ICEBLOWNDWEEVIL_F 0xFB
#define SPECIES_ICEBLOWNDWEEVIL_E 0xFC
#define SPECIES_ICEBLOWNDWEEVIL_W 0xFD
#define SPECIES_ICEBLOWNDWEEVIL_P 0xFE
#define SPECIES_MYSTERIOUSLIFEFORM 0xFF
#define SPECIES_MYSTERIOUSLIFEFORM_BULBORB 0x100
#define SPECIES_MYSTERIOUSLIFEFORM_AMPRAT 0x101
#define SPECIES_MYSTERIOUSLIFEFORM_DANDELFLY 0x102
#define SPECIES_MYSTERIOUSLIFEFORM_ARACHNODE 0x103
#define SPECIES_MYSTERIOUSLIFEFORM_BLOWHOG 0x104

#define SPECIES_JUMBOBULBORB_MEGA 0x105		//003
#define SPECIES_TITANBLOWHOG_MEGA 0x106		//006
#define SPECIES_MASTERHOP_MEGA 0x107		//009
#define SPECIES_GLINTBEETLE_MEGA 0x108		//012
#define SPECIES_DIRIGIBUG_MEGA 0x109		//015
#define SPECIES_GIANTBREADBUG_MEGA 0x10A		//021
#define SPECIES_SOVREIGNBULBLAX_MEGA 0x10B	//023
#define SPECIES_DANDELFLY_MEGA 0x10C		//027
#define SPECIES_PILEATEDSNAGRET_MEGA 0x10D	//030
#define SPECIES_DESICCATEDSKITTERLEAF_MEGA 0x10E //044
#define SPECIES_ADULTBULBMIN_MEGAB 0x10F		//059
#define SPECIES_ADULTBULBMIN_MEGAS 0x110		//059
#define SPECIES_MANATLEGS_MEGA 0x111		//066
#define SPECIES_VEHEAMOTHPHOSBAT_MEGA 0x112	//074
#define SPECIES_PYROCLASTICSLOOCH_MEGA 0x113	//086
#define SPECIES_GREATERSPOTTEDJELLYFLOAT_MEGA 0x114	//086
#define SPECIES_SNOWFLAKEFLUTTERTAIL_MEGA 0x115	//099
#define SPECIES_BOGSWALLOW_MEGA 0x116		//100
#define SPECIES_PUFFMIN_MEGA 0x117		//101
#define SPECIES_SCORCHCAKE_MEGA 0x118		//105
#define SPECIES_PUFFSTOOL_MEGA 0x119		//112
#define SPECIES_EMPRESSBULBLAX_MEGA 0x11A	//114
#define SPECIES_MUCKERSKATE_MEGA 0x11B		//116
#define SPECIES_GROOVYLONGLEGS_MEGA 0x11C	//117
#define SPECIES_CRUSTEDRUMPUP_MEGA 0x11D	//118
#define SPECIES_GATTLINGGROINK_MEGA 0x11E	//121
#define SPECIES_ARMOREDMAWDAD_MEGA 0x11F		//124
#define SPECIES_OATCHI_MEGA 0x120		//131
#define SPECIES_QUAGGLEDMIRECLOPS_MEGA 0x121	//132
#define SPECIES_WHITEPIKMIN_MEGA 0x122		//137
#define SPECIES_BLUEPIKMIN_MEGA 0x123		//138
#define SPECIES_ROCKPIKMIN_MEGA 0x124		//139
#define SPECIES_YELLOWPIKMIN_MEGA 0x125		//140
#define SPECIES_WINGEDPIKMIN_MEGA 0x126		//141
#define SPECIES_REDPIKMIN_MEGA 0x127		//142
#define SPECIES_PURPLEPIKMIN_MEGA 0x128		//143
#define SPECIES_ICEPIKMIN_MEGA 0x129		//147 
#define SPECIES_GLOWPIKMIN_MEGA 0x12A		//149
#define SPECIES_MOSS_MEGA 0x12B			//152
#define SPECIES_WATERYBLOWHOG_MEGA 0x12C	//170
#define SPECIES_OATCHI_MEGAB 0x12D		//131
#define SPECIES_MOSS_MEGAB 0x12E			//152
#define SPECIES_REDPIKMIN_VETERAN_MEGA 0x12F			//142

#define MURAL_PETEYPIRANNHA 0x130
#define MURAL_WHISKERPILLAR_MEGAB 0x131
#define MURAL_WHISKERPILLAR_MEGAS 0x132
#define MURAL_TOYPIKMIN_RED 0x133
#define MURAL_TOYPIKMIN_YELLOW 0x134
#define MURAL_TOYPIKMIN_BLUE 0x135
#define MURAL_PIKI_MALE 0x136
#define MURAL_PIKI_FEMALE 0x137
#define MURAL_DEMOF 0x138
#define MURAL_DEMOG 0x139
#define MURAL_DEMOI 0x13A
#define MURAL_DEMOW 0x13B
#define MURAL_USUALSUSPECT 0x13C
#define MURAL_METEOR 0x13D
#define MURAL_CHERRY 0x13E
#define MURAL_FIERYYOUNGYELLOWWOLLYHOP 0x13F
#define MURAL_HOTELTRANSYLVANIA 0x140
#define MURAL_HONEYWISP_MEGA 0x141
#define MURAL_CALYREX 0x142
#define MURAL_SKELEMIN 0x143
#define MURAL_SKELEMIN_MEGA 0x144
#define MURAL_MOYAIMIN 0x145
#define MURAL_MOYAIMIN_MEGA 0x146
#define MURAL_COCKATRICE 0x147
#define MURAL_BUPBORB 0x148
#define MURAL_DWARFKERMIT 0x149
#define MURAL_BULBLAXLARVA 0x14A
#define MURAL_COALBEETLE 0x14B
#define MURAL_HEAVYCANNONLARVA 0x14C
#define MURAL_CREWMATE 0x14D
#define MURAL_IMPOSTER 0x14E
#define MURAL_APACHE 0x14F
#define MURAL_MORSHUBUG 0x150
#define MURAL_SKITTERJUANA 0x151
#define MURAL_WAHPOLE 0x152
#define MURAL_WALUIGIWOG 0x153
#define MURAL_STEPHAN 0x154
#define MURAL_LINKGRET 0x155
#define MURAL_OLIMANATLEGS 0x156
#define MURAL_BULBEEL 0x157
#define MURAL_IWAGEN 0x158
#define MURAL_128MARIOS 0x159
#define MURAL_FIDDLEHEAD 0x15A
#define MURAL_HORSETAIL 0x15B
#define MURAL_SPOTCAP 0x15C
#define MURAL_KINGCAP 0x15D
#define MURAL_BULBIE 0x15E
#define MURAL_SLUGCAT 0x15F
#define MURAL_PINKELEBIT 0x160
#define MURAL_PRIMALASPID 0x161
#define MURAL_CHIBIROBO 0x162
#define MURAL_PIKACHU 0x163

#define SPECIES_WHISKERPILLAR_MEGAB 0x164
#define SPECIES_WHISKERPILLAR_MEGAS 0x165
#define SPECIES_PETEYPIRANNHA 0x166
#define SPECIES_TOYPIKMIN_RED 0x167
#define SPECIES_TOYPIKMIN_YELLOW 0x168
#define SPECIES_TOYPIKMIN_BLUE 0x169
#define SPECIES_PIKI_MALE 0x16A
#define SPECIES_PIKI_FEMALE 0x16B
#define SPECIES_DEMOF 0x16C
#define SPECIES_DEMOG 0x16D
#define SPECIES_DEMOI 0x16E
#define SPECIES_DEMOW 0x16F
#define SPECIES_USUALSUSPECT 0x170
#define SPECIES_METEOR 0x171
#define SPECIES_CHERRY 0x172
#define SPECIES_FIERYYOUNGYELLOWWOLLYHOP 0x173
#define SPECIES_HOTELTRANSYLVANIA 0x174
#define SPECIES_HONEYWISP_MEGA 0x175
#define SPECIES_CALYREX 0x176
#define SPECIES_SKELEMIN 0x177
#define SPECIES_SKELEMIN_MEGA 0x178
#define SPECIES_MOYAIMIN 0x179
#define SPECIES_MOYAIMIN_MEGA 0x17A
#define SPECIES_COCKATRICE 0x17B
#define SPECIES_BUPBORB 0x17C
#define SPECIES_DWARFKERMIT 0x17D
#define SPECIES_BULBLAXLARVA 0x17E
#define SPECIES_COALBEETLE 0x17F
#define SPECIES_HEAVYCANNONLARVA 0x180
#define SPECIES_CREWMATE 0x181
#define SPECIES_IMPOSTER 0x182
#define SPECIES_APACHE 0x183
#define SPECIES_MORSHUBUG 0x184
#define SPECIES_SKITTERJUANA 0x185
#define SPECIES_WAHPOLE 0x186
#define SPECIES_WALUIGIWOG 0x187
#define SPECIES_STEPHAN 0x188
#define SPECIES_LINKGRET 0x189
#define SPECIES_OLIMANATLEGS 0x18A
#define SPECIES_BULBEEL 0x18B
#define SPECIES_IWAGEN 0x18C
#define SPECIES_128MARIOS 0x18D
#define SPECIES_FIDDLEHEAD 0x18E
#define SPECIES_HORSETAIL 0x18F
#define SPECIES_SPOTCAP 0x190
#define SPECIES_KINGCAP 0x191
#define SPECIES_BULBIE 0x192
#define SPECIES_SLUGCAT 0x193
#define SPECIES_PINKELEBIT 0x194
#define SPECIES_PRIMALASPID 0x195
#define SPECIES_CHIBIROBO 0x196
#define SPECIES_PIKACHU 0x197


#define NUM_SPECIES (SPECIES_PIKACHU + 1)
