#include "../defines.h"
#include "../../include/follower_mon_sprites.h"
#include "../../include/new/character_customization.h"

// Add Followers Frames Here
MON_OW_TEMPLATE_32x32_FRAMES(0001, BulborbLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0002, Bulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0003, JumboBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0004, FieryBlowlet)
MON_OW_TEMPLATE_32x32_FRAMES(0005, FieryBlowhog)
MON_OW_TEMPLATE_64x64_FRAMES(0006, TitanBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0007, Wolpole)
MON_OW_TEMPLATE_32x32_FRAMES(0008, YellowWollyhop)
MON_OW_TEMPLATE_32x32_FRAMES(0009, Masterhop)
MON_OW_TEMPLATE_32x32_FRAMES(0010, FlintBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0011, Doodlebug)
MON_OW_TEMPLATE_32x32_FRAMES(0012, GlintBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0013, SwoopingSnitchbug)
MON_OW_TEMPLATE_32x32_FRAMES(0014, BumblingSnitchbug)
MON_OW_TEMPLATE_32x32_FRAMES(0015, Dirigibug)
MON_OW_TEMPLATE_32x32_FRAMES(0016, SnowBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0017, DwarfFrostyBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0018, FrostyBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0019, Crumbug)
MON_OW_TEMPLATE_32x32_FRAMES(0020, Breadbug)
MON_OW_TEMPLATE_32x32_FRAMES(0021, GiantBreadbug)
MON_OW_TEMPLATE_32x32_FRAMES(0022, EmperorBulblax)
MON_OW_TEMPLATE_32x32_FRAMES(0023, SovreignBulblax)
MON_OW_TEMPLATE_32x32_FRAMES(0024, DwarfBulbear)
MON_OW_TEMPLATE_32x32_FRAMES(0025, Bulbear)
MON_OW_TEMPLATE_32x32_FRAMES(0026, Honeywisp)
MON_OW_TEMPLATE_32x32_FRAMES(0027, Dandelfly)
MON_OW_TEMPLATE_32x32_FRAMES(0028, DownySnagret)
MON_OW_TEMPLATE_32x32_FRAMES(0029, BurrowingSnagret)
MON_OW_TEMPLATE_32x32_FRAMES(0030, PileatedSnagret)
MON_OW_TEMPLATE_32x32_FRAMES(0031, FemaleSheargrub)
MON_OW_TEMPLATE_32x32_FRAMES(0032, SwarmingSheargrub)
MON_OW_TEMPLATE_32x32_FRAMES(0033, MamaSheargrub)
MON_OW_TEMPLATE_32x32_FRAMES(0034, MaleSheargrub)
MON_OW_TEMPLATE_32x32_FRAMES(0035, Shearwig)
MON_OW_TEMPLATE_32x32_FRAMES(0036, QueenShearwig)
MON_OW_TEMPLATE_32x32_FRAMES(0037, AristocrabOffspring)
MON_OW_TEMPLATE_32x32_FRAMES(0038, PeckishAristocrab)
MON_OW_TEMPLATE_32x32_FRAMES(0039, Goolix)
MON_OW_TEMPLATE_32x32_FRAMES(0040, Foolix)
MON_OW_TEMPLATE_32x32_FRAMES(0041, ArcticCannonLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0042, ArcticCannonBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0043, Skitterleaf)
MON_OW_TEMPLATE_32x32_FRAMES(0044, DesiccatedSkitterleaf)
MON_OW_TEMPLATE_32x32_FRAMES(0045, ArmoredCannonLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0046, ArmoredCannonBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0047, HornedCannonBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0048, CreepingChrysanthemum)
MON_OW_TEMPLATE_32x32_FRAMES(0049, StartleSpore)
MON_OW_TEMPLATE_32x32_FRAMES(0050, HermitCrawmad)
MON_OW_TEMPLATE_32x32_FRAMES(0051, BugEyedCrawmad)
MON_OW_TEMPLATE_32x32_FRAMES(0052, DwarfBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0053, DwarfOrangeBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0054, BeadyLonLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0055, RagingLongLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0056, BaldyLongLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0057, ShaggyLongLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0058, Bulbmin)
MON_OW_TEMPLATE_32x32_FRAMES(0059, AdultBulbmin)
MON_OW_TEMPLATE_32x32_FRAMES(0060, Scornet)
MON_OW_TEMPLATE_32x32_FRAMES(0061, ScornetMaestro)
MON_OW_TEMPLATE_32x32_FRAMES(0062, BurrowNit)
MON_OW_TEMPLATE_32x32_FRAMES(0063, Joustmite)
MON_OW_TEMPLATE_32x32_FRAMES(0064, FlightyJoustmite)
MON_OW_TEMPLATE_32x32_FRAMES(0065, VolatileDweevil)
MON_OW_TEMPLATE_32x32_FRAMES(0066, ManAtLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0067, Skutterchuck)
MON_OW_TEMPLATE_32x32_FRAMES(0068, CalcifiedCrushblat)
MON_OW_TEMPLATE_32x32_FRAMES(0069, Arachnode)
MON_OW_TEMPLATE_32x32_FRAMES(0070, MoldyDwarfBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0071, MoldySlooch)
MON_OW_TEMPLATE_32x32_FRAMES(0072, Toxstool)
MON_OW_TEMPLATE_32x32_FRAMES(0073, Phosbat)
MON_OW_TEMPLATE_32x32_FRAMES(0074, VeheamothPhosbat)
MON_OW_TEMPLATE_32x32_FRAMES(0075, PuckeringBlinnow)
MON_OW_TEMPLATE_32x32_FRAMES(0076, Sputtlefish)
MON_OW_TEMPLATE_32x32_FRAMES(0077, Pricklepuff)
MON_OW_TEMPLATE_32x32_FRAMES(0078, Ujadani)
MON_OW_TEMPLATE_32x32_FRAMES(0079, Mitite)
MON_OW_TEMPLATE_32x32_FRAMES(0080, WitheringBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0081, PuffyBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0082, MiniatureSnootwhacker)
MON_OW_TEMPLATE_32x32_FRAMES(0083, MammothSnootwhacker)
MON_OW_TEMPLATE_32x32_FRAMES(0084, PyroclasticSlooch)
MON_OW_TEMPLATE_32x32_FRAMES(0085, LesserSpottedJellyfloat)
MON_OW_TEMPLATE_32x32_FRAMES(0086, GreaterSpottedJellyfloat)
MON_OW_TEMPLATE_32x32_FRAMES(0087, ToadyBloyster)
MON_OW_TEMPLATE_32x32_FRAMES(0088, RangingBloyster)
MON_OW_TEMPLATE_32x32_FRAMES(0089, SnowyBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0090, BlizzardingBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0091, Gildemandwee)
MON_OW_TEMPLATE_32x32_FRAMES(0092, Gildemander)
MON_OW_TEMPLATE_32x32_FRAMES(0093, Waddlequaff)
MON_OW_TEMPLATE_32x32_FRAMES(0094, Grubchucker)
MON_OW_TEMPLATE_32x32_FRAMES(0095, PearlyClamclamp)
MON_OW_TEMPLATE_32x32_FRAMES(0096, Sunsquish)
MON_OW_TEMPLATE_32x32_FRAMES(0097, Porquillion)
MON_OW_TEMPLATE_32x32_FRAMES(0098, TuskedBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0099, SnowflakeFluttertail)
MON_OW_TEMPLATE_32x32_FRAMES(0100, Bogswallow)
MON_OW_TEMPLATE_32x32_FRAMES(0101, Puffmin)
MON_OW_TEMPLATE_32x32_FRAMES(0102, Wollyhop)
MON_OW_TEMPLATE_32x32_FRAMES(0103, Chillyhop)
MON_OW_TEMPLATE_32x32_FRAMES(0104, BloomcapBloyster)
MON_OW_TEMPLATE_32x32_FRAMES(0105, Scorchcake)
MON_OW_TEMPLATE_32x32_FRAMES(0106, WaterDumple)
MON_OW_TEMPLATE_32x32_FRAMES(0107, LongWaterDumple)
MON_OW_TEMPLATE_32x32_FRAMES(0108, Mockiwi)
MON_OW_TEMPLATE_32x32_FRAMES(0109, CrestedMockiwi)
MON_OW_TEMPLATE_32x32_FRAMES(0110, ElongatedCrushblat)
MON_OW_TEMPLATE_32x32_FRAMES(0111, Puffstalk)
MON_OW_TEMPLATE_32x32_FRAMES(0112, Puffstool)
MON_OW_TEMPLATE_32x32_FRAMES(0113, AnodeBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0114, EmpressBulblax)
MON_OW_TEMPLATE_32x32_FRAMES(0115, Skeeterskate)
MON_OW_TEMPLATE_32x32_FRAMES(0116, Muckerskate)
MON_OW_TEMPLATE_32x32_FRAMES(0117, GroovyLongLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0118, CrustedRumpup)
MON_OW_TEMPLATE_32x32_FRAMES(0119, BeardedAmprat)
MON_OW_TEMPLATE_32x32_FRAMES(0120, FieryBulblax)
MON_OW_TEMPLATE_32x32_FRAMES(0121, GattlingGroink)
MON_OW_TEMPLATE_32x32_FRAMES(0122, Armurk)
MON_OW_TEMPLATE_32x32_FRAMES(0123, SegmentedCrawbster)
MON_OW_TEMPLATE_32x32_FRAMES(0124, ArmoredMawdad)
MON_OW_TEMPLATE_32x32_FRAMES(0125, SandbelchingMeerslug)
MON_OW_TEMPLATE_32x32_FRAMES(0126, ClickingSlurker)
MON_OW_TEMPLATE_32x32_FRAMES(0127, LuringSlurker)
MON_OW_TEMPLATE_32x32_FRAMES(0128, MedusalSlurker)
MON_OW_TEMPLATE_32x32_FRAMES(0129, PelletPosy)
MON_OW_TEMPLATE_32x32_FRAMES(0130, MasterOnion)
MON_OW_TEMPLATE_32x32_FRAMES(0131, Oatchi)
MON_OW_TEMPLATE_32x32_FRAMES(0132, QuaggledMireclops)
MON_OW_TEMPLATE_32x32_FRAMES(0133, AlbinoDwarfBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0134, HairyBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0135, WhiptongueBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0136, OrangeBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0137, WhitePikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0138, BluePikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0139, RockPikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0140, YellowPikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0141, WingedPikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0142, RedPikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0143, PurplePikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0144, WaterWraith)
MON_OW_TEMPLATE_32x32_FRAMES(0145, TitanDweevil)
MON_OW_TEMPLATE_32x32_FRAMES(0146, PlasmWraith)
MON_OW_TEMPLATE_32x32_FRAMES(0147, IcePikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0148, GlowSeed)
MON_OW_TEMPLATE_32x32_FRAMES(0149, GlowPikmin)
MON_OW_TEMPLATE_32x32_FRAMES(0150, SmokyProgg)
MON_OW_TEMPLATE_32x32_FRAMES(0151, Mamuta)
MON_OW_TEMPLATE_32x32_FRAMES(0152, Moss)
MON_OW_TEMPLATE_32x32_FRAMES(0153, ToyBorb)
MON_OW_TEMPLATE_32x32_FRAMES(0154, Bulblord)
MON_OW_TEMPLATE_32x32_FRAMES(0155, Pinchipede)
MON_OW_TEMPLATE_32x32_FRAMES(0156, LargeMothWollyhop)
MON_OW_TEMPLATE_32x32_FRAMES(0157, ToyBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0158, TelescopingPumphog)
MON_OW_TEMPLATE_32x32_FRAMES(0159, Beeb)
MON_OW_TEMPLATE_32x32_FRAMES(0160, BladedBeeb)
MON_OW_TEMPLATE_32x32_FRAMES(0161, StuddedBeeb)
MON_OW_TEMPLATE_32x32_FRAMES(0162, FireflapBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0163, IceblownDweevil)
MON_OW_TEMPLATE_32x32_FRAMES(0164, Spectralid)
MON_OW_TEMPLATE_32x32_FRAMES(0165, Blubbug)
MON_OW_TEMPLATE_32x32_FRAMES(0166, PuffyBlubbug)
MON_OW_TEMPLATE_32x32_FRAMES(0167, StuffedBellbloom)
MON_OW_TEMPLATE_32x32_FRAMES(0168, Centipare)
MON_OW_TEMPLATE_32x32_FRAMES(0169, AdultCentipare)
MON_OW_TEMPLATE_32x32_FRAMES(0170, WateryBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0171, Grabbit)
MON_OW_TEMPLATE_32x32_FRAMES(0172, Coppeller)
MON_OW_TEMPLATE_32x32_FRAMES(0173, Muggonfly)
MON_OW_TEMPLATE_32x32_FRAMES(0174, ElectricCottonade)
MON_OW_TEMPLATE_32x32_FRAMES(0175, Waddlepus)
MON_OW_TEMPLATE_32x32_FRAMES(0176, CrammedWraith)
MON_OW_TEMPLATE_32x32_FRAMES(0177, BerserkLeechHydroe)
MON_OW_TEMPLATE_32x32_FRAMES(0178, PebblePitcher)
MON_OW_TEMPLATE_32x32_FRAMES(0189, AncientSirehound)
MON_OW_TEMPLATE_32x32_FRAMES(0180, CourageReactor)
MON_OW_TEMPLATE_32x32_FRAMES(0181, AssembledCourage)
MON_OW_TEMPLATE_32x32_FRAMES(0182, RememberedOldBuddy)
MON_OW_TEMPLATE_32x32_FRAMES(0183, BulborbWithAGun)
MON_OW_TEMPLATE_32x32_FRAMES(0184, Kirby)
MON_OW_TEMPLATE_32x32_FRAMES(0185, Soul)
MON_OW_TEMPLATE_32x32_FRAMES(0000, PlaceholderLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0186, Demo77)
MON_OW_TEMPLATE_32x32_FRAMES(0187, Usuba)
MON_OW_TEMPLATE_32x32_FRAMES(0188, Kakureimo)
MON_OW_TEMPLATE_32x32_FRAMES(0189, Pikutabe)
MON_OW_TEMPLATE_32x32_FRAMES(0190, NamaPongashi)
MON_OW_TEMPLATE_32x32_FRAMES(0191, ChappyProto)
MON_OW_TEMPLATE_32x32_FRAMES(0412, Egg)
MON_OW_TEMPLATE_32x32_FRAMES(0192, RedBubblimp)
MON_OW_TEMPLATE_32x32_FRAMES(0193, Starnacle)
MON_OW_TEMPLATE_32x32_FRAMES(0194, Shearflea)
MON_OW_TEMPLATE_32x32_FRAMES(0195, WhiskerPillar)
MON_OW_TEMPLATE_32x32_FRAMES(0196, IcyBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0212, Freezecake)
MON_OW_TEMPLATE_32x32_FRAMES(0213, Shockcake)
MON_OW_TEMPLATE_32x32_FRAMES(0214, WideMouthedAnodeBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0215, DecoratedCannonBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0208, AntennaBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0142, RedPikminVeteran)
MON_OW_TEMPLATE_32x32_FRAMES(0145, TitanDweevilElectric)
MON_OW_TEMPLATE_32x32_FRAMES(0145, TitanDweevilFire)
MON_OW_TEMPLATE_32x32_FRAMES(0145, TitanDweevilPoison)
MON_OW_TEMPLATE_32x32_FRAMES(0145, TitanDweevilWater)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidRed)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidYellow)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidUnmarked)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidUnmarkedRed)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidUnmarkedPurple)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidElectric)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidHey0)
MON_OW_TEMPLATE_32x32_FRAMES(0165, SpectralidHey1)
MON_OW_TEMPLATE_32x32_FRAMES(0179, AncientSirehoundIce)
MON_OW_TEMPLATE_32x32_FRAMES(0179, AncientSirehoundElectric)
MON_OW_TEMPLATE_32x32_FRAMES(0179, AncientSirehoundFire)
MON_OW_TEMPLATE_32x32_FRAMES(0179, AncientSirehoundGloom)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyFlying)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyGrass)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyBug)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyPoison)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyWater)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyIce)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyFire)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyElectric)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyFighting)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyRock)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyGround)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyPsychic)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyGhost)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyDragon)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyDark)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbySteel)
MON_OW_TEMPLATE_32x32_FRAMES(0184, KirbyFairy)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulRed)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulYellow)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulBlue)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulPurple)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulWhite)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulRock)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulWinged)
MON_OW_TEMPLATE_32x32_FRAMES(0185, SoulIce)
MON_OW_TEMPLATE_32x32_FRAMES(0164, IceblownDweevilFire)
MON_OW_TEMPLATE_32x32_FRAMES(0164, IceblownDweevilElectric)
MON_OW_TEMPLATE_32x32_FRAMES(0164, IceblownDweevilWater)
MON_OW_TEMPLATE_32x32_FRAMES(0164, IceblownDweevilPoison)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeForm)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeFormBulborb)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeFormAmprat)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeFormDandelfly)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeFormArachnode)
MON_OW_TEMPLATE_32x32_FRAMES(0197, MysteriousLifeFormBlowhog)
MON_OW_TEMPLATE_32x32_FRAMES(0198, PeteyPirannha)
MON_OW_TEMPLATE_32x32_FRAMES(0199, ToyPikminRed)
MON_OW_TEMPLATE_32x32_FRAMES(0199, ToyPikminYellow)
MON_OW_TEMPLATE_32x32_FRAMES(0199, ToyPikminBlue)
MON_OW_TEMPLATE_32x32_FRAMES(0200, PikiMale)
MON_OW_TEMPLATE_32x32_FRAMES(0200, PikiFemale)
MON_OW_TEMPLATE_32x32_FRAMES(0201, DemoF)
MON_OW_TEMPLATE_32x32_FRAMES(0202, DemoG)
MON_OW_TEMPLATE_32x32_FRAMES(0203, DemoI)
MON_OW_TEMPLATE_32x32_FRAMES(0204, DemoW)
MON_OW_TEMPLATE_32x32_FRAMES(0205, UsualSuspect)
MON_OW_TEMPLATE_32x32_FRAMES(0206, Meteor)
MON_OW_TEMPLATE_32x32_FRAMES(0207, Cherry)
MON_OW_TEMPLATE_32x32_FRAMES(0209, FieryYoungYellowWollyhop)
MON_OW_TEMPLATE_32x32_FRAMES(0210, HotelTransylvania)
MON_OW_TEMPLATE_32x32_FRAMES(0211, Calyrex)
MON_OW_TEMPLATE_32x32_FRAMES(0216, Skelemin)
MON_OW_TEMPLATE_32x32_FRAMES(0217, Moyaimin)
MON_OW_TEMPLATE_32x32_FRAMES(0218, Cockatrice)
MON_OW_TEMPLATE_32x32_FRAMES(0219, Bupborb)
MON_OW_TEMPLATE_32x32_FRAMES(0220, DwarfKermit)
MON_OW_TEMPLATE_32x32_FRAMES(0221, BulblaxLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0222, CoalBeetle)
MON_OW_TEMPLATE_32x32_FRAMES(0223, HeavyCannonLarva)
MON_OW_TEMPLATE_32x32_FRAMES(0224, Crewmate)
MON_OW_TEMPLATE_32x32_FRAMES(0225, Imposter)
MON_OW_TEMPLATE_32x32_FRAMES(0226, Apache)
MON_OW_TEMPLATE_32x32_FRAMES(0227, Morshubug)
MON_OW_TEMPLATE_32x32_FRAMES(0228, Skitterjuana)
MON_OW_TEMPLATE_32x32_FRAMES(0229, Wahpole)
MON_OW_TEMPLATE_32x32_FRAMES(0230, Waluigiwog)
MON_OW_TEMPLATE_32x32_FRAMES(0231, Stephan)
MON_OW_TEMPLATE_32x32_FRAMES(0232, Linkgret)
MON_OW_TEMPLATE_32x32_FRAMES(0233, OliManAtLegs)
MON_OW_TEMPLATE_32x32_FRAMES(0234, Bulbeel)
MON_OW_TEMPLATE_32x32_FRAMES(0235, Iwagen)
MON_OW_TEMPLATE_32x32_FRAMES(0236, 128Marios)
MON_OW_TEMPLATE_32x32_FRAMES(0237, Fiddlehead)
MON_OW_TEMPLATE_32x32_FRAMES(0238, Horsetail)
MON_OW_TEMPLATE_32x32_FRAMES(0239, Spotcap)
MON_OW_TEMPLATE_32x32_FRAMES(0240, Kingcap)
MON_OW_TEMPLATE_32x32_FRAMES(0241, Bulbie)
MON_OW_TEMPLATE_32x32_FRAMES(0242, Slugcat)
MON_OW_TEMPLATE_32x32_FRAMES(0243, PinkElebit)
MON_OW_TEMPLATE_32x32_FRAMES(0244, PrimalAspid)
MON_OW_TEMPLATE_32x32_FRAMES(0245, ChibiRobo)
MON_OW_TEMPLATE_32x32_FRAMES(0246, Pikachu)
MON_OW_TEMPLATE_32x32_FRAMES(0150, SmokyProgMaster)

// Add Followers Graphics Info Here
const struct EventObjectGraphicsInfo gFollowerMonGfxTable0[] =
{
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBORBLARVA, BulborbLarva) // 0
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBORB, Bulborb)     // 1
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_JUMBOBULBORB, JumboBulborb) // 2
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIERYBLOWLET, FieryBlowlet)     // 3
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIERYBLOWHOG, FieryBlowhog)     // 4
    MON_OW_OBJECT_GRAPHICS_64(OBJ_EVENT_PAL_TAG_TITANBLOWHOG, TitanBlowhog) // 5
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WOLPOLE, Wolpole)     // 6
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_YELLOWWOLLYHOP, YellowWollyhop) // 7
    MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MASTERHOP, Masterhop) // 8
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FLINTBEETLE, FlintBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DOODLEBUG, Doodlebug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GLINTBEETLE, GlintBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SWOOPINGSNITCHBUG, SwoopingSnitchbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BUMBLINGSNITCHBUG, BumblingSnitchbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DIRIGIBUG, Dirigibug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SNOWBULBORB, SnowBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DWARFFROSTYBULBORB, DwarfFrostyBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FROSTYBULBORB, FrostyBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CRUMBUG, Crumbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BREADBUG, Breadbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GIANTBREADBUG, GiantBreadbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_EMPERORBULBLAX, EmperorBulblax)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOVREIGNBULBLAX, SovreignBulblax)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DWARFBULBEAR, DwarfBulbear)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPOTTYBULBEAR, Bulbear)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HONEYWISP, Honeywisp)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DANDELFLY, Dandelfly)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DOWNYSNAGRET, DownySnagret)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BURROWINGSNAGRET, BurrowingSnagret)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PILEATEDSNAGRET, PileatedSnagret)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FEMALESHEARGRUB, FemaleSheargrub)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SWARMINGSHEARGRUB, SwarmingSheargrub)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MAMASHEARGRUB, MamaSheargrub)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MALESHEARGRUB, MaleSheargrub)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SHEARWIG, Shearwig)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_QUEENSHEARWIG, QueenShearwig)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARISTOCRABOFFSPRING, AristocrabOffspring)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARISTOCRAB, PeckishAristocrab)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GOOLIX, Goolix)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FOOLIX, Foolix)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARCTICCANNONLARVA, ArcticCannonLarva)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARCTICCANNONBEETLE, ArcticCannonBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SKITTERLEAF, Skitterleaf)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DESICCATEDSKITTERLEAF, DesiccatedSkitterleaf)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARMOREDCANNONLARVA, ArmoredCannonLarva)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARMOREDCANNONBEETLE, ArmoredCannonBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HORNEDCANNONBEETLE, HornedCannonBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CREEPINGCHRYSANTHEMUM, CreepingChrysanthemum)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_STARTLESPORE, StartleSpore)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HERMITCRAWMAD, HermitCrawmad)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BUGEYEDCRAWMAD, BugEyedCrawmad)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DWARFBULBORB, DwarfBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DWARFORANGEBULBORB, DwarfOrangeBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BEADYLONGLEGS, BeadyLonLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_RAGINGLONGLEGS, RagingLongLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BALDYLONGLEGS, BaldyLongLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SHAGGYLONGLEGS, ShaggyLongLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBMIN, Bulbmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ADULTBULBMIN, AdultBulbmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SCORNET, Scornet)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SCORNETMAESTRO, ScornetMaestro) 
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BURROWNIT, BurrowNit)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_JOUSTMITE, Joustmite)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FLIGHTYJOUSTMITE, FlightyJoustmite) 
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_VOLATILEDWEEVIL, VolatileDweevil)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MANATLEGS, ManAtLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SKUTTERCHUCK, Skutterchuck)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CALCIFIEDCRUSHBLAT, CalcifiedCrushblat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARACHNODE, Arachnode)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MOLDYDWARFBULBORB, MoldyDwarfBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MOLDYSLOOCH, MoldySlooch)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOXSTOOL, Toxstool)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PHOSBAT, Phosbat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_VEHEAMOTHPHOSBAT, VeheamothPhosbat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUCKERINGBLINNOW, PuckeringBlinnow)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPUTTLEFISH, Sputtlefish)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PRICKLEPUFF, Pricklepuff)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_UJADANI, Ujadani)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MITITE, Mitite)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WITHERINGBLOWHOG, WitheringBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUFFYBLOWHOG, PuffyBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MINIATURESNOOTWHACKER, MiniatureSnootwhacker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MAMMOTHSNOOTWHACKER, MammothSnootwhacker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PYROCLASTICSLOOCH, PyroclasticSlooch)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_LESSERSPOTTEDJELLYFLOAT, LesserSpottedJellyfloat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GREATERSPOTTEDJELLYFLOAT, GreaterSpottedJellyfloat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOADYBLOYSTER, ToadyBloyster)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_RANGINGBLOYSTER, RangingBloyster)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SNOWYBLOWHOG, SnowyBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BLIZZARDINGBLOWHOG, BlizzardingBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GILDEMANDWEE, Gildemandwee)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GILDEMANDER, Gildemander)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WADDLEQUAFF, Waddlequaff)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GRUBCHUCKER, Grubchucker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PEARLYCLAMCLAMP, PearlyClamclamp)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SUNQUISH, Sunsquish)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PROQUILLION, Porquillion)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TUSKEDBLOWHOG, TuskedBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SNOWFLAKEFLUTTERTAIL, SnowflakeFluttertail)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BOGSWALLOW, Bogswallow)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUFFMIN, Puffmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WOLLYHOP, Wollyhop)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CHILLYHOP, Chillyhop)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BLOOMCAPBLOYSTER, BloomcapBloyster) 
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SCORCHCAKE, Scorchcake)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WATERDUMPLE, WaterDumple)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_LONGWATERDUMPLE, LongWaterDumple)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MOCKIWI, Mockiwi)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CRESTEDMOCKIWI, CrestedMockiwi) 
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ELONGATEDCRUSHBLAT, ElongatedCrushblat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUFFSTALK, Puffstalk)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUFFSTOOL, Puffstool)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANODEBEETLE, AnodeBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_EMPRESSBULBLAX, EmpressBulblax)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SKEETERSKATE, Skeeterskate)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MUCKERSKATE, Muckerskate)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GROOVYLONGLEGS, GroovyLongLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CRUSTEDRUMPUP, CrustedRumpup)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BEARDEDAMPRAT, BeardedAmprat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIERYBULBLAX, FieryBulblax)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GATTLINGGROINK, GattlingGroink)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARMURK, Armurk)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SEGMENTEDCRAWBSTER, SegmentedCrawbster) 
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ARMOREDMAWDAD, ArmoredMawdad)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SANDBELCHINGMEERSLUG, SandbelchingMeerslug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CLICKINGSLURKER, ClickingSlurker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_LURINGSLURKER, LuringSlurker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MEDUSALSLURKER, MedusalSlurker)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PELLETPOSY, PelletPosy)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MASTERONION, MasterOnion)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_OATCHI, Oatchi)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_QUAGGLEDMIRECLOPS, QuaggledMireclops)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ALBINODWARFBULBORB, AlbinoDwarfBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HAIRYBULBORB, HairyBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WHIPTONGUEBULBORB, WhiptongueBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ORANGEBULBORB, OrangeBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WHITEPIKMIN, WhitePikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BLUEPIKMIN, BluePikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ROCKPIKMIN, RockPikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_YELLOWPIKMIN, YellowPikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WINGEDPIKMIN, WingedPikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_REDPIKMIN, RedPikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PURPLEPIKMIN, PurplePikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WATERWRAITH, WaterWraith)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TITANDWEEVIL, TitanDweevil)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PLASMWRAITH, PlasmWraith)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEPIKMIN, IcePikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GLOWSEED, GlowSeed)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GLOWPIKMIN, GlowPikmin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SMOKYPROGG, SmokyProgg)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MAMUTA, Mamuta)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MOSS, Moss)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOYBORB, ToyBorb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBLORD, Bulblord)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PINCHIPEDE, Pinchipede)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_LARGEMOUTHWOLLYHOP, LargeMothWollyhop)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOYBLOWHOG, ToyBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TELESCOPINGPUMPHOG, TelescopingPumphog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BEEB, Beeb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BLADEDBEEB, BladedBeeb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_STUDDEDBEEB, StuddedBeeb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIREFLAPBULBORB, FireflapBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL, IceblownDweevil)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID, Spectralid)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BLUBBUG, Blubbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PUFFYBLUBBUG, PuffyBlubbug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_STUFFEDBELLBLOOM, StuffedBellbloom)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CENTIPARE, Centipare)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ADULTCENTIPARE, AdultCentipare)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WATERYBLOWHOG, WateryBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_GRABBIT, Grabbit)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_COPPELLER, Coppeller)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MUGGONFLY, Muggonfly)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ELECTRICCOTTONADE, ElectricCottonade)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WADDLEPUS, Waddlepus)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CRAMMEDWRAITH, CrammedWraith)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BERSERKLEECHHYDROE, BerserkLeechHydroe)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PEBBLEPITCHER, PebblePitcher)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND, AncientSirehound)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_COURAGEREACTOR, CourageReactor)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ASSEMBLEDCOURAGE, AssembledCourage)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_REMEMBEREDOLDBUDDY, RememberedOldBuddy)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBORBWITHAGUN, BulborbWithAGun)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY, Kirby)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL, Soul)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PLACEHOLDERLARVA, PlaceholderLarva)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DEMO77, Demo77)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_USUBA, Usuba)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KAKUREIMO, Kakureimo)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PIKUTABE, Pikutabe)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_NAMAPONGASHI, NamaPongashi)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CHAPPYPROTO, ChappyProto)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_EGG, Egg)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_REDBUBBLIMP, RedBubblimp)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_STARNACLE, Starnacle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SHEARFLEA, Shearflea)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WHISKERPILLAR, WhiskerPillar)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICYBLOWHOG, IcyBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FREEZECAKE, Freezecake)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SHOCKCAKE, Shockcake)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WIDEMOUTHEDANODEBEETLE, WideMouthedAnodeBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DECORATEDCANNONBEETLE, DecoratedCannonBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANTENNABEETLE, AntennaBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_REDPIKMIN_VETERAN, RedPikminVeteran)		//142
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TITANDWEEVIL_ELECTRIC, TitanDweevilElectric)	//145
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TITANDWEEVIL_FIRE, TitanDweevilFire)		//145
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TITANDWEEVIL_POISON, TitanDweevilPoison)	//145
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TITANDWEEVIL_WATER, TitanDweevilWater)		//145
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_RED, SpectralidRed)		//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_YELLOW, SpectralidYellow)		//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKED, SpectralidUnmarked)	//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKEDRED, SpectralidUnmarkedRed)	//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKEDPURPLE, SpectralidUnmarkedPurple)	//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_ELECTRIC, SpectralidElectric)	//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_HEY0, SpectralidHey0)		//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPECTRALID_HEY1, SpectralidHey1)		//164
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_ICE, AncientSirehoundIce)	//179
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_ELECTRIC, AncientSirehoundElectric)	//179
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_FIRE, AncientSirehoundFire)	//179
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_GLOOM, AncientSirehoundGloom)	//179
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_FLYING, KirbyFlying)		//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_GRASS, KirbyGrass)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_BUG, KirbyBug)//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_POISON, KirbyPoison)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_WATER, KirbyWater)		//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_ICE, KirbyIce)//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_FIRE, KirbyFire)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_ELECTRIC, KirbyElectric)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_FIGHTING, KirbyFighting)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_ROCK, KirbyRock)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_GROUND, KirbyGround)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_PSYCHIC, KirbyPsychic)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_GHOST, KirbyGhost)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_DRAGON, KirbyDragon)//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_DARK, KirbyDark)//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_STEEL, KirbySteel)	//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KIRBY_FAIRY, KirbyFairy)//184
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_RED, SoulRed)		//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_YELLOW, SoulYellow)		//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_BLUE, SoulBlue)			//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_PURPLE, SoulPurple)		//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_WHITE, SoulWhite)		//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_ROCK, SoulRock)			//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_WINGED, SoulWinged)		//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SOUL_ICE, SoulIce)			//185
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_F, IceblownDweevilFire)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_E, IceblownDweevilElectric)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_W, IceblownDweevilWater)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_P, IceblownDweevilPoison)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM, MysteriousLifeForm)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_BULBORB, MysteriousLifeFormBulborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_AMPRAT, MysteriousLifeFormAmprat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_DANDELFLY, MysteriousLifeFormDandelfly)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_ARACHNODE, MysteriousLifeFormArachnode)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_BLOWHOG, MysteriousLifeFormBlowhog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PETEYPIRANNHA, PeteyPirannha)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOYPIKMIN_RED, ToyPikminRed)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOYPIKMIN_YELLOW, ToyPikminYellow)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_TOYPIKMIN_BLUE, ToyPikminBlue)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PIKI_MALE, PikiMale)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PIKI_FEMALE, PikiFemale)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DEMOF, DemoF)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DEMOG, DemoG)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DEMOI, DemoI)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DEMOW, DemoW)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_USUALSUSPECT, UsualSuspect)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_METEOR, Meteor)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CHERRY, Cherry)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIERYYOUNGYELLOWWOLLYHOP, FieryYoungYellowWollyhop)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HOTELTRANSYLVANIA, HotelTransylvania)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CALYREX, Calyrex)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SKELEMIN, Skelemin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MOYAIMIN, Moyaimin)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_COCKATRICE, Cockatrice)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BUPBORB, Bupborb)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_DWARFKERMIT, DwarfKermit)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBLAXLARVA, BulblaxLarva)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_COALBEETLE, CoalBeetle)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HEAVYCANNONLARVA, HeavyCannonLarva)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CREWMATE, Crewmate)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_IMPOSTER, Imposter)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_APACHE, Apache)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_MORSHUBUG, Morshubug)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SKITTERJUANA, Skitterjuana)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WAHPOLE, Wahpole)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_WALUIGIWOG, Waluigiwog)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_STEPHAN, Stephan)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_LINKGRET, Linkgret)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_OLIMANATLEGS, OliManAtLegs)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBEEL, Bulbeel)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_IWAGEN, Iwagen)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_128MARIOS, 128Marios)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_FIDDLEHEAD, Fiddlehead)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_HORSETAIL, Horsetail)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SPOTCAP, Spotcap)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_KINGCAP, Kingcap)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_BULBIE, Bulbie)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SLUGCAT, Slugcat)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PINKELEBIT, PinkElebit)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PRIMALASPID, PrimalAspid)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_CHIBIROBO, ChibiRobo)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_PIKACHU, Pikachu)
	MON_OW_OBJECT_GRAPHICS_32(OBJ_EVENT_PAL_TAG_SMOKYPROG_MASTER, SmokyProgMaster)
};

// Link Species with Overworld Sprites
const u16 gFollowerMonSpriteIdTable[] =
{
    [SPECIES_BULBORBLARVA]  = EVENT_OBJ_GFX_BULBORBLARVA,
    [SPECIES_BULBORB]    = EVENT_OBJ_GFX_BULBORB,
    [SPECIES_JUMBOBULBORB]  = EVENT_OBJ_GFX_JUMBOBULBORB,
    [SPECIES_FIERYBLOWLET]    = EVENT_OBJ_GFX_FIERYBLOWLET,
    [SPECIES_FIERYBLOWHOG]    = EVENT_OBJ_GFX_FIERYBLOWHOG,
    [SPECIES_TITANBLOWHOG]  = EVENT_OBJ_GFX_TITANBLOWHOG,
    [SPECIES_WOLPOLE]    = EVENT_OBJ_GFX_WOLPOLE,
    [SPECIES_YELLOWWOLLYHOP]  = EVENT_OBJ_GFX_YELLOWWOLLYHOP,
    [SPECIES_MASTERHOP]  = EVENT_OBJ_GFX_MASTERHOP,
	[SPECIES_FLINTBEETLE] 		= EVENT_OBJ_GFX_FLINTBEETLE,
	[SPECIES_DOODLEBUG] 		= EVENT_OBJ_GFX_DOODLEBUG,
	[SPECIES_GLINTBEETLE] 		= EVENT_OBJ_GFX_GLINTBEETLE,
	[SPECIES_SWOOPINGSNITCHBUG] 	= EVENT_OBJ_GFX_SWOOPINGSNITCHBUG,
	[SPECIES_BUMBLINGSNITCHBUG] 	= EVENT_OBJ_GFX_BUMBLINGSNITCHBUG,
	[SPECIES_DIRIGIBUG] 		= EVENT_OBJ_GFX_DIRIGIBUG,
	[SPECIES_SNOWBULBORB] 		= EVENT_OBJ_GFX_SNOWBULBORB,
	[SPECIES_DWARFFROSTYBULBORB] 	= EVENT_OBJ_GFX_DWARFFROSTYBULBORB,
	[SPECIES_FROSTYBULBORB] 		= EVENT_OBJ_GFX_FROSTYBULBORB,
	[SPECIES_CRUMBUG] 			= EVENT_OBJ_GFX_CRUMBUG,
	[SPECIES_BREADBUG] 			= EVENT_OBJ_GFX_BREADBUG,
	[SPECIES_GIANTBREADBUG] 		= EVENT_OBJ_GFX_GIANTBREADBUG,
	[SPECIES_EMPERORBULBLAX] 		= EVENT_OBJ_GFX_EMPERORBULBLAX,
	[SPECIES_SOVREIGNBULBLAX] 		= EVENT_OBJ_GFX_SOVREIGNBULBLAX,
	[SPECIES_DWARFBULBEAR] 		= EVENT_OBJ_GFX_DWARFBULBEAR,
	[SPECIES_SPOTTYBULBEAR] 		= EVENT_OBJ_GFX_SPOTTYBULBEAR,
	[SPECIES_HONEYWISP] 		= EVENT_OBJ_GFX_HONEYWISP,
	[SPECIES_DANDELFLY] 		= EVENT_OBJ_GFX_DANDELFLY,
	[SPECIES_DOWNYSNAGRET] 		= EVENT_OBJ_GFX_DOWNYSNAGRET,
	[SPECIES_BURROWINGSNAGRET] 		= EVENT_OBJ_GFX_BURROWINGSNAGRET,
	[SPECIES_PILEATEDSNAGRET] 		= EVENT_OBJ_GFX_PILEATEDSNAGRET,
	[SPECIES_FEMALESHEARGRUB] 		= EVENT_OBJ_GFX_FEMALESHEARGRUB,
	[SPECIES_SWARMINGSHEARGRUB] 	= EVENT_OBJ_GFX_SWARMINGSHEARGRUB,
	[SPECIES_MAMASHEARGRUB] 		= EVENT_OBJ_GFX_MAMASHEARGRUB,
	[SPECIES_MALESHEARGRUB] 		= EVENT_OBJ_GFX_MALESHEARGRUB,
	[SPECIES_SHEARWIG] 			= EVENT_OBJ_GFX_SHEARWIG,
	[SPECIES_QUEENSHEARWIG] 		= EVENT_OBJ_GFX_QUEENSHEARWIG,
	[SPECIES_ARISTOCRABOFFSPRING] 	= EVENT_OBJ_GFX_ARISTOCRABOFFSPRING,
	[SPECIES_ARISTOCRAB] 		= EVENT_OBJ_GFX_ARISTOCRAB,
	[SPECIES_GOOLIX] 			= EVENT_OBJ_GFX_GOOLIX,
	[SPECIES_FOOLIX] 			= EVENT_OBJ_GFX_FOOLIX,
	[SPECIES_ARCTICCANNONLARVA] 	= EVENT_OBJ_GFX_ARCTICCANNONLARVA,
	[SPECIES_ARCTICCANNONBEETLE] 	= EVENT_OBJ_GFX_ARCTICCANNONBEETLE,
	[SPECIES_SKITTERLEAF] 		= EVENT_OBJ_GFX_SKITTERLEAF,
	[SPECIES_DESICCATEDSKITTERLEAF] 	= EVENT_OBJ_GFX_DESICCATEDSKITTERLEAF,
	[SPECIES_ARMOREDCANNONLARVA] 	= EVENT_OBJ_GFX_ARMOREDCANNONLARVA,
	[SPECIES_ARMOREDCANNONBEETLE] 	= EVENT_OBJ_GFX_ARMOREDCANNONBEETLE,
	[SPECIES_HORNEDCANNONBEETLE] 	= EVENT_OBJ_GFX_HORNEDCANNONBEETLE,
	[SPECIES_CREEPINGCHRYSANTHEMUM] 	= EVENT_OBJ_GFX_CREEPINGCHRYSANTHEMUM,
	[SPECIES_STARTLESPORE] 		= EVENT_OBJ_GFX_STARTLESPORE,
	[SPECIES_HERMITCRAWMAD] 		= EVENT_OBJ_GFX_HERMITCRAWMAD,
	[SPECIES_BUGEYEDCRAWMAD] 		= EVENT_OBJ_GFX_BUGEYEDCRAWMAD,
	[SPECIES_DWARFBULBORB] 		= EVENT_OBJ_GFX_DWARFBULBORB,
	[SPECIES_DWARFORANGEBULBORB] 	= EVENT_OBJ_GFX_DWARFORANGEBULBORB,
	[SPECIES_BEADYLONGLEGS] 		= EVENT_OBJ_GFX_BEADYLONGLEGS,
	[SPECIES_RAGINGLONGLEGS] 		= EVENT_OBJ_GFX_RAGINGLONGLEGS,
	[SPECIES_BALDYLONGLEGS] 		= EVENT_OBJ_GFX_BALDYLONGLEGS,
	[SPECIES_SHAGGYLONGLEGS] 		= EVENT_OBJ_GFX_SHAGGYLONGLEGS,
	[SPECIES_BULBMIN] 			= EVENT_OBJ_GFX_BULBMIN,
	[SPECIES_ADULTBULBMIN] 		= EVENT_OBJ_GFX_ADULTBULBMIN,
	[SPECIES_SCORNET] 			= EVENT_OBJ_GFX_SCORNET,
	[SPECIES_SCORNETMAESTRO] 		= EVENT_OBJ_GFX_SCORNETMAESTRO,
	[SPECIES_BURROWNIT] 		= EVENT_OBJ_GFX_BURROWNIT,
	[SPECIES_JOUSTMITE] 		= EVENT_OBJ_GFX_JOUSTMITE,
	[SPECIES_FLIGHTYJOUSTMITE] 		= EVENT_OBJ_GFX_FLIGHTYJOUSTMITE,
	[SPECIES_VOLATILEDWEEVIL] 		= EVENT_OBJ_GFX_VOLATILEDWEEVIL,
	[SPECIES_MANATLEGS] 		= EVENT_OBJ_GFX_MANATLEGS,
	[SPECIES_SKUTTERCHUCK] 		= EVENT_OBJ_GFX_SKUTTERCHUCK,
	[SPECIES_CALCIFIEDCRUSHBLAT] 	= EVENT_OBJ_GFX_CALCIFIEDCRUSHBLAT,
	[SPECIES_ARACHNODE] 		= EVENT_OBJ_GFX_ARACHNODE,
	[SPECIES_MOLDYDWARFBULBORB] 	= EVENT_OBJ_GFX_MOLDYDWARFBULBORB,
	[SPECIES_MOLDYSLOOCH] 		= EVENT_OBJ_GFX_MOLDYSLOOCH,
	[SPECIES_TOXSTOOL] 			= EVENT_OBJ_GFX_TOXSTOOL,
	[SPECIES_PHOSBAT] 			= EVENT_OBJ_GFX_PHOSBAT,
	[SPECIES_VEHEAMOTHPHOSBAT] 		= EVENT_OBJ_GFX_VEHEAMOTHPHOSBAT,
	[SPECIES_PUCKERINGBLINNOW] 		= EVENT_OBJ_GFX_PUCKERINGBLINNOW,
	[SPECIES_SPUTTLEFISH] 		= EVENT_OBJ_GFX_SPUTTLEFISH,
	[SPECIES_PRICKLEPUFF] 		= EVENT_OBJ_GFX_PRICKLEPUFF,
	[SPECIES_UJADANI] 			= EVENT_OBJ_GFX_UJADANI,
	[SPECIES_MITITE] 			= EVENT_OBJ_GFX_MITITE,
	[SPECIES_WITHERINGBLOWHOG] 		= EVENT_OBJ_GFX_WITHERINGBLOWHOG,
	[SPECIES_PUFFYBLOWHOG] 		= EVENT_OBJ_GFX_PUFFYBLOWHOG,
	[SPECIES_MINIATURESNOOTWHACKER] 	= EVENT_OBJ_GFX_MINIATURESNOOTWHACKER,
	[SPECIES_MAMMOTHSNOOTWHACKER] 	= EVENT_OBJ_GFX_MAMMOTHSNOOTWHACKER,
	[SPECIES_PYROCLASTICSLOOCH] 	= EVENT_OBJ_GFX_PYROCLASTICSLOOCH,
	[SPECIES_LESSERSPOTTEDJELLYFLOAT] 	= EVENT_OBJ_GFX_LESSERSPOTTEDJELLYFLOAT,
	[SPECIES_GREATERSPOTTEDJELLYFLOAT] 	= EVENT_OBJ_GFX_GREATERSPOTTEDJELLYFLOAT,
	[SPECIES_TOADYBLOYSTER] 		= EVENT_OBJ_GFX_TOADYBLOYSTER,
	[SPECIES_RANGINGBLOYSTER] 		= EVENT_OBJ_GFX_RANGINGBLOYSTER,
	[SPECIES_SNOWYBLOWHOG] 		= EVENT_OBJ_GFX_SNOWYBLOWHOG,
	[SPECIES_BLIZZARDINGBLOWHOG] 	= EVENT_OBJ_GFX_BLIZZARDINGBLOWHOG,
	[SPECIES_GILDEMANDWEE] 		= EVENT_OBJ_GFX_GILDEMANDWEE,
	[SPECIES_GILDEMANDER] 		= EVENT_OBJ_GFX_GILDEMANDER,
	[SPECIES_WADDLEQUAFF] 		= EVENT_OBJ_GFX_WADDLEQUAFF,
	[SPECIES_GRUBCHUCKER] 		= EVENT_OBJ_GFX_GRUBCHUCKER,
	[SPECIES_PEARLYCLAMCLAMP] 		= EVENT_OBJ_GFX_PEARLYCLAMCLAMP,
	[SPECIES_SUNQUISH] 			= EVENT_OBJ_GFX_SUNQUISH,
	[SPECIES_PROQUILLION] 		= EVENT_OBJ_GFX_PROQUILLION,
	[SPECIES_TUSKEDBLOWHOG] 		= EVENT_OBJ_GFX_TUSKEDBLOWHOG,
	[SPECIES_SNOWFLAKEFLUTTERTAIL] 	= EVENT_OBJ_GFX_SNOWFLAKEFLUTTERTAIL,
	[SPECIES_BOGSWALLOW] 		= EVENT_OBJ_GFX_BOGSWALLOW,
	[SPECIES_PUFFMIN] 			= EVENT_OBJ_GFX_PUFFMIN,
	[SPECIES_WOLLYHOP] 			= EVENT_OBJ_GFX_WOLLYHOP,
	[SPECIES_CHILLYHOP] 		= EVENT_OBJ_GFX_CHILLYHOP,
	[SPECIES_BLOOMCAPBLOYSTER] 		= EVENT_OBJ_GFX_BLOOMCAPBLOYSTER,
	[SPECIES_SCORCHCAKE] 		= EVENT_OBJ_GFX_SCORCHCAKE,
	[SPECIES_WATERDUMPLE] 		= EVENT_OBJ_GFX_WATERDUMPLE,
	[SPECIES_LONGWATERDUMPLE] 		= EVENT_OBJ_GFX_LONGWATERDUMPLE,
	[SPECIES_MOCKIWI] 			= EVENT_OBJ_GFX_MOCKIWI,
	[SPECIES_CRESTEDMOCKIWI] 		= EVENT_OBJ_GFX_CRESTEDMOCKIWI,
	[SPECIES_ELONGATEDCRUSHBLAT] 	= EVENT_OBJ_GFX_ELONGATEDCRUSHBLAT,
	[SPECIES_PUFFSTALK] 		= EVENT_OBJ_GFX_PUFFSTALK,
	[SPECIES_PUFFSTOOL] 		= EVENT_OBJ_GFX_PUFFSTOOL,
	[SPECIES_ANODEBEETLE] 		= EVENT_OBJ_GFX_ANODEBEETLE,
	[SPECIES_EMPRESSBULBLAX] 		= EVENT_OBJ_GFX_EMPRESSBULBLAX,
	[SPECIES_SKEETERSKATE] 		= EVENT_OBJ_GFX_SKEETERSKATE,
	[SPECIES_MUCKERSKATE] 		= EVENT_OBJ_GFX_MUCKERSKATE,
	[SPECIES_GROOVYLONGLEGS] 		= EVENT_OBJ_GFX_GROOVYLONGLEGS,
	[SPECIES_CRUSTEDRUMPUP] 		= EVENT_OBJ_GFX_CRUSTEDRUMPUP,
	[SPECIES_BEARDEDAMPRAT] 		= EVENT_OBJ_GFX_BEARDEDAMPRAT,
	[SPECIES_FIERYBULBLAX] 		= EVENT_OBJ_GFX_FIERYBULBLAX,
	[SPECIES_GATTLINGGROINK] 		= EVENT_OBJ_GFX_GATTLINGGROINK,
	[SPECIES_ARMURK] 			= EVENT_OBJ_GFX_ARMURK,
	[SPECIES_SEGMENTEDCRAWBSTER] 	= EVENT_OBJ_GFX_SEGMENTEDCRAWBSTER,
	[SPECIES_ARMOREDMAWDAD] 		= EVENT_OBJ_GFX_ARMOREDMAWDAD,
	[SPECIES_SANDBELCHINGMEERSLUG] 	= EVENT_OBJ_GFX_SANDBELCHINGMEERSLUG,
	[SPECIES_CLICKINGSLURKER] 		= EVENT_OBJ_GFX_CLICKINGSLURKER,
	[SPECIES_LURINGSLURKER] 		= EVENT_OBJ_GFX_LURINGSLURKER,
	[SPECIES_MEDUSALSLURKER] 		= EVENT_OBJ_GFX_MEDUSALSLURKER,
	[SPECIES_PELLETPOSY] 		= EVENT_OBJ_GFX_PELLETPOSY,
	[SPECIES_MASTERONION] 		= EVENT_OBJ_GFX_MASTERONION,
	[SPECIES_OATCHI] 			= EVENT_OBJ_GFX_OATCHI,
	[SPECIES_QUAGGLEDMIRECLOPS] 	= EVENT_OBJ_GFX_QUAGGLEDMIRECLOPS,
	[SPECIES_ALBINODWARFBULBORB] 	= EVENT_OBJ_GFX_ALBINODWARFBULBORB,
	[SPECIES_HAIRYBULBORB] 		= EVENT_OBJ_GFX_HAIRYBULBORB,
	[SPECIES_WHIPTONGUEBULBORB] 	= EVENT_OBJ_GFX_WHIPTONGUEBULBORB,
	[SPECIES_ORANGEBULBORB] 		= EVENT_OBJ_GFX_ORANGEBULBORB,
	[SPECIES_WHITEPIKMIN] 		= EVENT_OBJ_GFX_WHITEPIKMIN,
	[SPECIES_BLUEPIKMIN] 		= EVENT_OBJ_GFX_BLUEPIKMIN,
	[SPECIES_ROCKPIKMIN] 		= EVENT_OBJ_GFX_ROCKPIKMIN,
	[SPECIES_YELLOWPIKMIN] 		= EVENT_OBJ_GFX_YELLOWPIKMIN,
	[SPECIES_WINGEDPIKMIN] 		= EVENT_OBJ_GFX_WINGEDPIKMIN,
	[SPECIES_REDPIKMIN] 		= EVENT_OBJ_GFX_REDPIKMIN,
	[SPECIES_PURPLEPIKMIN] 		= EVENT_OBJ_GFX_PURPLEPIKMIN,
	[SPECIES_WATERWRAITH] 		= EVENT_OBJ_GFX_WATERWRAITH,
	[SPECIES_TITANDWEEVIL] 		= EVENT_OBJ_GFX_TITANDWEEVIL,
	[SPECIES_PLASMWRAITH] 		= EVENT_OBJ_GFX_PLASMWRAITH,
	[SPECIES_ICEPIKMIN] 		= EVENT_OBJ_GFX_ICEPIKMIN,
	[SPECIES_GLOWSEED] 			= EVENT_OBJ_GFX_GLOWSEED,
	[SPECIES_GLOWPIKMIN] 		= EVENT_OBJ_GFX_GLOWPIKMIN,
	[SPECIES_SMOKYPROGG] 		= EVENT_OBJ_GFX_SMOKYPROGG,
	[SPECIES_MAMUTA] 			= EVENT_OBJ_GFX_MAMUTA,
	[SPECIES_MOSS] 			= EVENT_OBJ_GFX_MOSS,
	[SPECIES_TOYBORB] 			= EVENT_OBJ_GFX_TOYBORB,
	[SPECIES_BULBLORD] 			= EVENT_OBJ_GFX_BULBLORD,
	[SPECIES_PINCHIPEDE] 		= EVENT_OBJ_GFX_PINCHIPEDE,
	[SPECIES_LARGEMOUTHWOLLYHOP] 	= EVENT_OBJ_GFX_LARGEMOUTHWOLLYHOP,
	[SPECIES_TOYBLOWHOG] 		= EVENT_OBJ_GFX_TOYBLOWHOG,
	[SPECIES_TELESCOPINGPUMPHOG] 	= EVENT_OBJ_GFX_TELESCOPINGPUMPHOG,
	[SPECIES_BEEB] 			= EVENT_OBJ_GFX_BEEB,
	[SPECIES_BLADEDBEEB] 		= EVENT_OBJ_GFX_BLADEDBEEB,
	[SPECIES_STUDDEDBEEB] 		= EVENT_OBJ_GFX_STUDDEDBEEB,
	[SPECIES_FIREFLAPBULBORB] 		= EVENT_OBJ_GFX_FIREFLAPBULBORB,
	[SPECIES_ICEBLOWNDWEEVIL] 		= EVENT_OBJ_GFX_ICEBLOWNDWEEVIL,
	[SPECIES_SPECTRALID] 		= EVENT_OBJ_GFX_SPECTRALID,
	[SPECIES_BLUBBUG] 			= EVENT_OBJ_GFX_BLUBBUG,
	[SPECIES_PUFFYBLUBBUG] 		= EVENT_OBJ_GFX_PUFFYBLUBBUG,
	[SPECIES_STUFFEDBELLBLOOM] 		= EVENT_OBJ_GFX_STUFFEDBELLBLOOM,
	[SPECIES_CENTIPARE] 		= EVENT_OBJ_GFX_CENTIPARE,
	[SPECIES_ADULTCENTIPARE] 		= EVENT_OBJ_GFX_ADULTCENTIPARE,
	[SPECIES_WATERYBLOWHOG] 		= EVENT_OBJ_GFX_WATERYBLOWHOG,
	[SPECIES_GRABBIT] 			= EVENT_OBJ_GFX_GRABBIT,
	[SPECIES_COPPELLER] 		= EVENT_OBJ_GFX_COPPELLER,
	[SPECIES_MUGGONFLY] 		= EVENT_OBJ_GFX_MUGGONFLY,
	[SPECIES_ELECTRICCOTTONADE] 	= EVENT_OBJ_GFX_ELECTRICCOTTONADE,
	[SPECIES_WADDLEPUS] 		= EVENT_OBJ_GFX_WADDLEPUS,
	[SPECIES_CRAMMEDWRAITH] 		= EVENT_OBJ_GFX_CRAMMEDWRAITH,
	[SPECIES_BERSERKLEECHHYDROE] 	= EVENT_OBJ_GFX_BERSERKLEECHHYDROE,
	[SPECIES_PEBBLEPITCHER] 		= EVENT_OBJ_GFX_PEBBLEPITCHER,
	[SPECIES_ANCIENTSIREHOUND] 		= EVENT_OBJ_GFX_ANCIENTSIREHOUND,
	[SPECIES_COURAGEREACTOR] 		= EVENT_OBJ_GFX_COURAGEREACTOR,
	[SPECIES_ASSEMBLEDCOURAGE] 		= EVENT_OBJ_GFX_ASSEMBLEDCOURAGE,
	[SPECIES_REMEMBEREDOLDBUDDY] 	= EVENT_OBJ_GFX_REMEMBEREDOLDBUDDY,
	[SPECIES_BULBORBWITHAGUN] 		= EVENT_OBJ_GFX_BULBORBWITHAGUN,
	[SPECIES_KIRBY] 			= EVENT_OBJ_GFX_KIRBY,
	[SPECIES_SOUL] 			= EVENT_OBJ_GFX_SOUL,
	[SPECIES_PLACEHOLDERLARVA] 		= EVENT_OBJ_GFX_PLACEHOLDERLARVA,
	[SPECIES_DEMO77] 			= EVENT_OBJ_GFX_DEMO77,
	[SPECIES_USUBA] 			= EVENT_OBJ_GFX_USUBA,
	[SPECIES_KAKUREIMO] 		= EVENT_OBJ_GFX_KAKUREIMO,
	[SPECIES_PIKUTABE] 			= EVENT_OBJ_GFX_PIKUTABE,
	[SPECIES_NAMAPONGASHI] 		= EVENT_OBJ_GFX_NAMAPONGASHI,
	[SPECIES_CHAPPYPROTO] 		= EVENT_OBJ_GFX_CHAPPYPROTO,

	[SPECIES_EGG] 			= EVENT_OBJ_GFX_EGG,

	[SPECIES_GILDEMANDWEE_NOGOLD] 	= EVENT_OBJ_GFX_GILDEMANDWEE,
	[SPECIES_GILDEMANDER_NOGOLD] 	= EVENT_OBJ_GFX_GILDEMANDER,
	[SPECIES_BEARDEDAMPRAT_STATIC] 	= EVENT_OBJ_GFX_BEARDEDAMPRAT,
	[SPECIES_REDPIKMIN_VETERAN] 	= EVENT_OBJ_GFX_REDPIKMIN_VETERAN,
	[SPECIES_TITANDWEEVIL_ELECTRIC] 	= EVENT_OBJ_GFX_TITANDWEEVIL_ELECTRIC,
	[SPECIES_TITANDWEEVIL_FIRE] 	= EVENT_OBJ_GFX_TITANDWEEVIL_FIRE,
	[SPECIES_TITANDWEEVIL_POISON] 	= EVENT_OBJ_GFX_TITANDWEEVIL_POISON,
	[SPECIES_TITANDWEEVIL_WATER] 	= EVENT_OBJ_GFX_TITANDWEEVIL_WATER,
	[SPECIES_SMOKYPROGG_MASTER] 	= EVENT_OBJ_GFX_SMOKYPROG_MASTER,
	[SPECIES_SPECTRALID_RED] 		= EVENT_OBJ_GFX_SPECTRALID_RED,
	[SPECIES_SPECTRALID_YELLOW] 	= EVENT_OBJ_GFX_SPECTRALID_YELLOW,
	[SPECIES_SPECTRALID_UNMARKED] 	= EVENT_OBJ_GFX_SPECTRALID_UNMARKED,
	[SPECIES_SPECTRALID_UNMARKEDRED] 	= EVENT_OBJ_GFX_SPECTRALID_UNMARKEDRED,
	[SPECIES_SPECTRALID_UNMARKEDPURPLE] = EVENT_OBJ_GFX_SPECTRALID_UNMARKEDPURPLE,
	[SPECIES_SPECTRALID_ELECTRIC] 	= EVENT_OBJ_GFX_SPECTRALID_ELECTRIC,
	[SPECIES_SPECTRALID_HEY0] 		= EVENT_OBJ_GFX_SPECTRALID_HEY0,
	[SPECIES_SPECTRALID_HEY1] 		= EVENT_OBJ_GFX_SPECTRALID_HEY1,
	[SPECIES_ANCIENTSIREHOUND_ICE] 	= EVENT_OBJ_GFX_ANCIENTSIREHOUND_ICE,
	[SPECIES_ANCIENTSIREHOUND_ELECTRIC] = EVENT_OBJ_GFX_ANCIENTSIREHOUND_ELECTRIC,
	[SPECIES_ANCIENTSIREHOUND_FIRE] 	= EVENT_OBJ_GFX_ANCIENTSIREHOUND_FIRE,
	[SPECIES_ANCIENTSIREHOUND_GLOOM] 	= EVENT_OBJ_GFX_ANCIENTSIREHOUND_GLOOM,
	[SPECIES_KIRBY_FLYING] 		= EVENT_OBJ_GFX_KIRBY_FLYING,
	[SPECIES_KIRBY_GRASS] 		= EVENT_OBJ_GFX_KIRBY_GRASS,
	[SPECIES_KIRBY_BUG] 		= EVENT_OBJ_GFX_KIRBY_BUG,
	[SPECIES_KIRBY_POISON] 		= EVENT_OBJ_GFX_KIRBY_POISON,
	[SPECIES_KIRBY_WATER] 		= EVENT_OBJ_GFX_KIRBY_WATER,
	[SPECIES_KIRBY_ICE] 		= EVENT_OBJ_GFX_KIRBY_ICE,
	[SPECIES_KIRBY_FIRE] 		= EVENT_OBJ_GFX_KIRBY_FIRE,
	[SPECIES_KIRBY_ELECTRIC] 		= EVENT_OBJ_GFX_KIRBY_ELECTRIC,
	[SPECIES_KIRBY_FIGHTING] 		= EVENT_OBJ_GFX_KIRBY_FIGHTING,
	[SPECIES_KIRBY_ROCK] 		= EVENT_OBJ_GFX_KIRBY_ROCK,
	[SPECIES_KIRBY_GROUND] 		= EVENT_OBJ_GFX_KIRBY_GROUND,
	[SPECIES_KIRBY_PSYCHIC] 		= EVENT_OBJ_GFX_KIRBY_PSYCHIC,
	[SPECIES_KIRBY_GHOST] 		= EVENT_OBJ_GFX_KIRBY_GHOST,
	[SPECIES_KIRBY_DRAGON] 		= EVENT_OBJ_GFX_KIRBY_DRAGON,
	[SPECIES_KIRBY_DARK] 		= EVENT_OBJ_GFX_KIRBY_DARK,
	[SPECIES_KIRBY_STEEL] 		= EVENT_OBJ_GFX_KIRBY_STEEL,
	[SPECIES_KIRBY_FAIRY]	 	= EVENT_OBJ_GFX_KIRBY_FAIRY,
	[SPECIES_SOUL_RED] 			= EVENT_OBJ_GFX_SOUL_RED,
	[SPECIES_SOUL_YELLOW] 		= EVENT_OBJ_GFX_SOUL_YELLOW,
	[SPECIES_SOUL_BLUE] 		= EVENT_OBJ_GFX_SOUL_BLUE,
	[SPECIES_SOUL_PURPLE] 		= EVENT_OBJ_GFX_SOUL_PURPLE,
	[SPECIES_SOUL_WHITE] 		= EVENT_OBJ_GFX_SOUL_WHITE,
	[SPECIES_SOUL_ROCK] 		= EVENT_OBJ_GFX_SOUL_ROCK,
	[SPECIES_SOUL_WINGED] 		= EVENT_OBJ_GFX_SOUL_WINGED,
	[SPECIES_SOUL_ICE] 			= EVENT_OBJ_GFX_SOUL_ICE,

	[SPECIES_JUMBOBULBORB_MEGA] 	= EVENT_OBJ_GFX_JUMBOBULBORB,
	[SPECIES_TITANBLOWHOG_MEGA] 	= EVENT_OBJ_GFX_TITANBLOWHOG,
	[SPECIES_MASTERHOP_MEGA] 		= EVENT_OBJ_GFX_MASTERHOP,
	[SPECIES_GLINTBEETLE_MEGA] 		= EVENT_OBJ_GFX_GLINTBEETLE,
	[SPECIES_DIRIGIBUG_MEGA] 		= EVENT_OBJ_GFX_DIRIGIBUG,		//15
	[SPECIES_GIANTBREADBUG_MEGA] 	= EVENT_OBJ_GFX_GIANTBREADBUG,
	[SPECIES_SOVREIGNBULBLAX_MEGA] 	= EVENT_OBJ_GFX_SOVREIGNBULBLAX,
	[SPECIES_DANDELFLY_MEGA] 		= EVENT_OBJ_GFX_DANDELFLY,
	[SPECIES_PILEATEDSNAGRET_MEGA] 	= EVENT_OBJ_GFX_PILEATEDSNAGRET,
	[SPECIES_DESICCATEDSKITTERLEAF_MEGA]= EVENT_OBJ_GFX_DESICCATEDSKITTERLEAF,	//44
	[SPECIES_ADULTBULBMIN_MEGAB] 	= EVENT_OBJ_GFX_ADULTBULBMIN,
	[SPECIES_ADULTBULBMIN_MEGAS] 	= EVENT_OBJ_GFX_ADULTBULBMIN,
	[SPECIES_MANATLEGS_MEGA] 		= EVENT_OBJ_GFX_MANATLEGS,
	[SPECIES_VEHEAMOTHPHOSBAT_MEGA] 	= EVENT_OBJ_GFX_VEHEAMOTHPHOSBAT,	//74
	[SPECIES_PYROCLASTICSLOOCH_MEGA] 	= EVENT_OBJ_GFX_PYROCLASTICSLOOCH,	//84
	[SPECIES_GREATERSPOTTEDJELLYFLOAT_MEGA] = EVENT_OBJ_GFX_GREATERSPOTTEDJELLYFLOAT,	//86
	[SPECIES_SNOWFLAKEFLUTTERTAIL_MEGA] = EVENT_OBJ_GFX_SNOWFLAKEFLUTTERTAIL,	//99
	[SPECIES_BOGSWALLOW_MEGA] 		= EVENT_OBJ_GFX_BOGSWALLOW,		//100
	[SPECIES_PUFFMIN_MEGA] 		= EVENT_OBJ_GFX_PUFFMIN,
	[SPECIES_SCORCHCAKE_MEGA] 		= EVENT_OBJ_GFX_SCORCHCAKE,		//105
	[SPECIES_PUFFSTOOL_MEGA] 		= EVENT_OBJ_GFX_PUFFSTOOL,		//112
	[SPECIES_EMPRESSBULBLAX_MEGA] 	= EVENT_OBJ_GFX_EMPRESSBULBLAX,
	[SPECIES_MUCKERSKATE_MEGA] 		= EVENT_OBJ_GFX_MUCKERSKATE,		//116
	[SPECIES_GROOVYLONGLEGS_MEGA] 	= EVENT_OBJ_GFX_GROOVYLONGLEGS,		//117
	[SPECIES_CRUSTEDRUMPUP_MEGA] 	= EVENT_OBJ_GFX_CRUSTEDRUMPUP,		//118
	[SPECIES_GATTLINGGROINK_MEGA] 	= EVENT_OBJ_GFX_GATTLINGGROINK,		//121
	[SPECIES_ARMOREDMAWDAD_MEGA] 	= EVENT_OBJ_GFX_ARMOREDMAWDAD,
	[SPECIES_OATCHI_MEGA] 		= EVENT_OBJ_GFX_OATCHI,
	[SPECIES_QUAGGLEDMIRECLOPS_MEGA] 	= EVENT_OBJ_GFX_QUAGGLEDMIRECLOPS,
	[SPECIES_WHITEPIKMIN_MEGA] 		= EVENT_OBJ_GFX_WHITEPIKMIN,
	[SPECIES_BLUEPIKMIN_MEGA] 		= EVENT_OBJ_GFX_BLUEPIKMIN,
	[SPECIES_ROCKPIKMIN_MEGA] 		= EVENT_OBJ_GFX_ROCKPIKMIN,
	[SPECIES_YELLOWPIKMIN_MEGA] 	= EVENT_OBJ_GFX_YELLOWPIKMIN,
	[SPECIES_WINGEDPIKMIN_MEGA] 	= EVENT_OBJ_GFX_WINGEDPIKMIN,
	[SPECIES_REDPIKMIN_MEGA] 		= EVENT_OBJ_GFX_REDPIKMIN,
	[SPECIES_PURPLEPIKMIN_MEGA] 	= EVENT_OBJ_GFX_PURPLEPIKMIN,
	[SPECIES_ICEPIKMIN_MEGA] 		= EVENT_OBJ_GFX_ICEPIKMIN,
	[SPECIES_GLOWPIKMIN_MEGA] 		= EVENT_OBJ_GFX_GLOWPIKMIN,
	[SPECIES_MOSS_MEGA] 		= EVENT_OBJ_GFX_MOSS,
	[SPECIES_WATERYBLOWHOG_MEGA] 	= EVENT_OBJ_GFX_WATERYBLOWHOG,		//170
	[SPECIES_OATCHI_MEGAB] 		= EVENT_OBJ_GFX_OATCHI,
	[SPECIES_MOSS_MEGAB] 		= EVENT_OBJ_GFX_MOSS,

	[SPECIES_ICEBLOWNDWEEVIL_F] 	= EVENT_OBJ_GFX_ICEBLOWNDWEEVIL_F,
	[SPECIES_ICEBLOWNDWEEVIL_E] 	= EVENT_OBJ_GFX_ICEBLOWNDWEEVIL_E,
	[SPECIES_ICEBLOWNDWEEVIL_W] 	= EVENT_OBJ_GFX_ICEBLOWNDWEEVIL_W,
	[SPECIES_ICEBLOWNDWEEVIL_P] 	= EVENT_OBJ_GFX_ICEBLOWNDWEEVIL_P,
	[SPECIES_REDBUBBLIMP] 		= EVENT_OBJ_GFX_REDBUBBLIMP,
	[SPECIES_STARNACLE] 		= EVENT_OBJ_GFX_STARNACLE,
	[SPECIES_SHEARFLEA] 		= EVENT_OBJ_GFX_SHEARFLEA,
	[SPECIES_WHISKERPILLAR] 		= EVENT_OBJ_GFX_WHISKERPILLAR,
	[SPECIES_ICYBLOWHOG] 		= EVENT_OBJ_GFX_ICYBLOWHOG,
	[SPECIES_MYSTERIOUSLIFEFORM] 		= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM,
	[SPECIES_MYSTERIOUSLIFEFORM_BULBORB] 	= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM_BULBORB,
	[SPECIES_MYSTERIOUSLIFEFORM_AMPRAT] 	= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM_AMPRAT,
	[SPECIES_MYSTERIOUSLIFEFORM_DANDELFLY] 	= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM_DANDELFLY,
	[SPECIES_MYSTERIOUSLIFEFORM_ARACHNODE] 	= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM_ARACHNODE,
	[SPECIES_MYSTERIOUSLIFEFORM_BLOWHOG] 	= EVENT_OBJ_GFX_MYSTERIOUSLIFEFORM_BLOWHOG,

	[SPECIES_WATERWRAITH_NOTIRES] = EVENT_OBJ_GFX_WATERWRAITH,
	[SPECIES_WHISKERPILLAR_MEGAB] = EVENT_OBJ_GFX_WHISKERPILLAR,
	[SPECIES_WHISKERPILLAR_MEGAS] = EVENT_OBJ_GFX_WHISKERPILLAR,
	[SPECIES_PETEYPIRANNHA] = EVENT_OBJ_GFX_PETEYPIRANNHA,
	[SPECIES_TOYPIKMIN_RED] = EVENT_OBJ_GFX_TOYPIKMIN_RED,
	[SPECIES_TOYPIKMIN_YELLOW] = EVENT_OBJ_GFX_TOYPIKMIN_YELLOW,
	[SPECIES_TOYPIKMIN_BLUE] = EVENT_OBJ_GFX_TOYPIKMIN_BLUE,
	[SPECIES_PIKI_MALE] = EVENT_OBJ_GFX_PIKI_MALE,
	[SPECIES_PIKI_FEMALE] = EVENT_OBJ_GFX_PIKI_FEMALE,
	[SPECIES_DEMOF] = EVENT_OBJ_GFX_DEMOF,
	[SPECIES_DEMOG] = EVENT_OBJ_GFX_DEMOG,
	[SPECIES_DEMOI] = EVENT_OBJ_GFX_DEMOI,
	[SPECIES_DEMOW] = EVENT_OBJ_GFX_DEMOW,
	[SPECIES_USUALSUSPECT] = EVENT_OBJ_GFX_USUALSUSPECT,
	[SPECIES_METEOR] = EVENT_OBJ_GFX_METEOR,
	[SPECIES_CHERRY] = EVENT_OBJ_GFX_CHERRY,
	[SPECIES_ANTENNABEETLE] = EVENT_OBJ_GFX_ANTENNABEETLE,
	[SPECIES_FIERYYOUNGYELLOWWOLLYHOP] = EVENT_OBJ_GFX_FIERYYOUNGYELLOWWOLLYHOP,
	[SPECIES_HOTELTRANSYLVANIA] = EVENT_OBJ_GFX_HOTELTRANSYLVANIA,
	[SPECIES_CALYREX] = EVENT_OBJ_GFX_CALYREX,
	[SPECIES_HONEYWISP_MEGA] = EVENT_OBJ_GFX_HONEYWISP,
	[SPECIES_FREEZECAKE] = EVENT_OBJ_GFX_FREEZECAKE,
	[SPECIES_SHOCKCAKE] = EVENT_OBJ_GFX_SHOCKCAKE,
	[SPECIES_WIDEMOUTHEDANODEBEETLE] = EVENT_OBJ_GFX_WIDEMOUTHEDANODEBEETLE,
	[SPECIES_DECORATEDCANNONBEETLE] = EVENT_OBJ_GFX_DECORATEDCANNONBEETLE,
	
	[SPECIES_REDPIKMIN_VETERAN_MEGA] = EVENT_OBJ_GFX_REDPIKMIN_VETERAN,
	
	[MURAL_WHISKERPILLAR_MEGAB] = EVENT_OBJ_GFX_WHISKERPILLAR,
	[MURAL_WHISKERPILLAR_MEGAS] = EVENT_OBJ_GFX_WHISKERPILLAR,
	[MURAL_PETEYPIRANNHA] = EVENT_OBJ_GFX_PETEYPIRANNHA,
	[MURAL_TOYPIKMIN_RED] = EVENT_OBJ_GFX_TOYPIKMIN_RED,
	[MURAL_TOYPIKMIN_YELLOW] = EVENT_OBJ_GFX_TOYPIKMIN_YELLOW,
	[MURAL_TOYPIKMIN_BLUE] = EVENT_OBJ_GFX_TOYPIKMIN_BLUE,
	[MURAL_PIKI_MALE] = EVENT_OBJ_GFX_PIKI_MALE,
	[MURAL_PIKI_FEMALE] = EVENT_OBJ_GFX_PIKI_FEMALE,
	[MURAL_DEMOF] = EVENT_OBJ_GFX_DEMOF,
	[MURAL_DEMOG] = EVENT_OBJ_GFX_DEMOG,
	[MURAL_DEMOI] = EVENT_OBJ_GFX_DEMOI,
	[MURAL_DEMOW] = EVENT_OBJ_GFX_DEMOW,
	[MURAL_USUALSUSPECT] = EVENT_OBJ_GFX_USUALSUSPECT,
	[MURAL_METEOR] = EVENT_OBJ_GFX_METEOR,
	[MURAL_CHERRY] = EVENT_OBJ_GFX_CHERRY,
	[MURAL_FIERYYOUNGYELLOWWOLLYHOP] = EVENT_OBJ_GFX_FIERYYOUNGYELLOWWOLLYHOP,
	[MURAL_HOTELTRANSYLVANIA] = EVENT_OBJ_GFX_HOTELTRANSYLVANIA,
	[MURAL_CALYREX] = EVENT_OBJ_GFX_CALYREX,
	[MURAL_HONEYWISP_MEGA] = EVENT_OBJ_GFX_HONEYWISP,

	[SPECIES_SKELEMIN] =    EVENT_OBJ_GFX_SKELEMIN,
	[SPECIES_SKELEMIN_MEGA] =    EVENT_OBJ_GFX_SKELEMIN,
	[SPECIES_MOYAIMIN] =    EVENT_OBJ_GFX_MOYAIMIN,
	[SPECIES_MOYAIMIN_MEGA] =    EVENT_OBJ_GFX_MOYAIMIN,
	[SPECIES_COCKATRICE] =    EVENT_OBJ_GFX_COCKATRICE,
	[SPECIES_BUPBORB] =    EVENT_OBJ_GFX_BUPBORB,
	[SPECIES_DWARFKERMIT] =    EVENT_OBJ_GFX_DWARFKERMIT,
	[SPECIES_BULBLAXLARVA] =    EVENT_OBJ_GFX_BULBLAXLARVA,
	[SPECIES_COALBEETLE] =    EVENT_OBJ_GFX_COALBEETLE,
	[SPECIES_HEAVYCANNONLARVA] =    EVENT_OBJ_GFX_HEAVYCANNONLARVA,
	[SPECIES_CREWMATE] =    EVENT_OBJ_GFX_CREWMATE,
	[SPECIES_IMPOSTER] =    EVENT_OBJ_GFX_IMPOSTER,
	[SPECIES_APACHE] =    EVENT_OBJ_GFX_APACHE,
	[SPECIES_MORSHUBUG] =    EVENT_OBJ_GFX_MORSHUBUG,
	[SPECIES_SKITTERJUANA] =    EVENT_OBJ_GFX_SKITTERJUANA,
	[SPECIES_WAHPOLE] =    EVENT_OBJ_GFX_WAHPOLE,
	[SPECIES_WALUIGIWOG] =    EVENT_OBJ_GFX_WALUIGIWOG,
	[SPECIES_STEPHAN] =    EVENT_OBJ_GFX_STEPHAN,
	[SPECIES_LINKGRET] =    EVENT_OBJ_GFX_LINKGRET,
	[SPECIES_OLIMANATLEGS] =    EVENT_OBJ_GFX_OLIMANATLEGS,
	[SPECIES_BULBEEL] =    EVENT_OBJ_GFX_BULBEEL,
	[SPECIES_IWAGEN] =    EVENT_OBJ_GFX_IWAGEN,
	[SPECIES_128MARIOS] =    EVENT_OBJ_GFX_128MARIOS,
	[SPECIES_FIDDLEHEAD] =    EVENT_OBJ_GFX_FIDDLEHEAD,
	[SPECIES_HORSETAIL] =    EVENT_OBJ_GFX_HORSETAIL,
	[SPECIES_SPOTCAP] =    EVENT_OBJ_GFX_SPOTCAP,
	[SPECIES_KINGCAP] =    EVENT_OBJ_GFX_KINGCAP,
	[SPECIES_BULBIE] =    EVENT_OBJ_GFX_BULBIE,
	[SPECIES_SLUGCAT] =    EVENT_OBJ_GFX_SLUGCAT,
	[SPECIES_PINKELEBIT] =    EVENT_OBJ_GFX_PINKELEBIT,
	[SPECIES_PRIMALASPID] =    EVENT_OBJ_GFX_PRIMALASPID,
	[SPECIES_CHIBIROBO] =    EVENT_OBJ_GFX_CHIBIROBO,
	[SPECIES_PIKACHU] =    EVENT_OBJ_GFX_PIKACHU,

	[MURAL_SKELEMIN] =    EVENT_OBJ_GFX_SKELEMIN,
	[MURAL_SKELEMIN_MEGA] =    EVENT_OBJ_GFX_SKELEMIN,
	[MURAL_MOYAIMIN] =    EVENT_OBJ_GFX_MOYAIMIN,
	[MURAL_MOYAIMIN_MEGA] =    EVENT_OBJ_GFX_MOYAIMIN,
	[MURAL_COCKATRICE] =    EVENT_OBJ_GFX_COCKATRICE,
	[MURAL_BUPBORB] =    EVENT_OBJ_GFX_BUPBORB,
	[MURAL_DWARFKERMIT] =    EVENT_OBJ_GFX_DWARFKERMIT,
	[MURAL_BULBLAXLARVA] =    EVENT_OBJ_GFX_BULBLAXLARVA,
	[MURAL_COALBEETLE] =    EVENT_OBJ_GFX_COALBEETLE,
	[MURAL_HEAVYCANNONLARVA] =    EVENT_OBJ_GFX_HEAVYCANNONLARVA,
	[MURAL_CREWMATE] =    EVENT_OBJ_GFX_CREWMATE,
	[MURAL_IMPOSTER] =    EVENT_OBJ_GFX_IMPOSTER,
	[MURAL_APACHE] =    EVENT_OBJ_GFX_APACHE,
	[MURAL_MORSHUBUG] =    EVENT_OBJ_GFX_MORSHUBUG,
	[MURAL_SKITTERJUANA] =    EVENT_OBJ_GFX_SKITTERJUANA,
	[MURAL_WAHPOLE] =    EVENT_OBJ_GFX_WAHPOLE,
	[MURAL_WALUIGIWOG] =    EVENT_OBJ_GFX_WALUIGIWOG,
	[MURAL_STEPHAN] =    EVENT_OBJ_GFX_STEPHAN,
	[MURAL_LINKGRET] =    EVENT_OBJ_GFX_LINKGRET,
	[MURAL_OLIMANATLEGS] =    EVENT_OBJ_GFX_OLIMANATLEGS,
	[MURAL_BULBEEL] =    EVENT_OBJ_GFX_BULBEEL,
	[MURAL_IWAGEN] =    EVENT_OBJ_GFX_IWAGEN,
	[MURAL_128MARIOS] =    EVENT_OBJ_GFX_128MARIOS,
	[MURAL_FIDDLEHEAD] =    EVENT_OBJ_GFX_FIDDLEHEAD,
	[MURAL_HORSETAIL] =    EVENT_OBJ_GFX_HORSETAIL,
	[MURAL_SPOTCAP] =    EVENT_OBJ_GFX_SPOTCAP,
	[MURAL_KINGCAP] =    EVENT_OBJ_GFX_KINGCAP,
	[MURAL_BULBIE] =    EVENT_OBJ_GFX_BULBIE,
	[MURAL_SLUGCAT] =    EVENT_OBJ_GFX_SLUGCAT,
	[MURAL_PINKELEBIT] =    EVENT_OBJ_GFX_PINKELEBIT,
	[MURAL_PRIMALASPID] =    EVENT_OBJ_GFX_PRIMALASPID,
	[MURAL_CHIBIROBO] =    EVENT_OBJ_GFX_CHIBIROBO,
	[MURAL_PIKACHU] =    EVENT_OBJ_GFX_PIKACHU,
};

static const union AnimCmd sMonAnim_FaceSouth[] =
{
    ANIMCMD_FRAME(0, 16),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_FaceNorth[] =
{
    ANIMCMD_FRAME(2, 16),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_FaceWest[] =
{
    ANIMCMD_FRAME(4, 16),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_FaceEast[] =
{
    ANIMCMD_FRAME(4, 16, .hFlip = TRUE),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoSouth[] =
{
    ANIMCMD_FRAME(0, 8),
    ANIMCMD_FRAME(1, 8),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoNorth[] =
{
    ANIMCMD_FRAME(2, 8),
    ANIMCMD_FRAME(3, 8),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoWest[] =
{
    ANIMCMD_FRAME(4, 8),
    ANIMCMD_FRAME(5, 8),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoEast[] =
{
    ANIMCMD_FRAME(4, 8, .hFlip = TRUE),
    ANIMCMD_FRAME(5, 8, .hFlip = TRUE),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastSouth[] =
{
    ANIMCMD_FRAME(0, 4),
    ANIMCMD_FRAME(1, 4),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastNorth[] =
{
    ANIMCMD_FRAME(2, 4),
    ANIMCMD_FRAME(3, 4),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastWest[] =
{
    ANIMCMD_FRAME(4, 4),
    ANIMCMD_FRAME(5, 4),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastEast[] =
{
    ANIMCMD_FRAME(4, 4, .hFlip = TRUE),
    ANIMCMD_FRAME(5, 4, .hFlip = TRUE),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFasterSouth[] =
{
    ANIMCMD_FRAME(0, 2),
    ANIMCMD_FRAME(1, 2),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFasterNorth[] =
{
    ANIMCMD_FRAME(2, 2),
    ANIMCMD_FRAME(3, 2),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFasterWest[] =
{
    ANIMCMD_FRAME(4, 2),
    ANIMCMD_FRAME(5, 2),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFasterEast[] =
{
    ANIMCMD_FRAME(4, 2, .hFlip = TRUE),
    ANIMCMD_FRAME(5, 2, .hFlip = TRUE),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastestSouth[] =
{
    ANIMCMD_FRAME(0, 1),
    ANIMCMD_FRAME(1, 1),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastestNorth[] =
{
    ANIMCMD_FRAME(2, 1),
    ANIMCMD_FRAME(3, 1),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastestWest[] =
{
    ANIMCMD_FRAME(4, 1),
    ANIMCMD_FRAME(5, 1),
    ANIMCMD_JUMP(0),
};

static const union AnimCmd sMonAnim_GoFastestEast[] =
{
    ANIMCMD_FRAME(4, 1, .hFlip = TRUE),
    ANIMCMD_FRAME(5, 1, .hFlip = TRUE),
    ANIMCMD_JUMP(0),
};

const union AnimCmd *const gFollowerMonAnimTable[] =
{
    [ANIM_STD_FACE_SOUTH]       = sMonAnim_FaceSouth,
    [ANIM_STD_FACE_NORTH]       = sMonAnim_FaceNorth,
    [ANIM_STD_FACE_WEST]        = sMonAnim_FaceWest,
    [ANIM_STD_FACE_EAST]        = sMonAnim_FaceEast,
    [ANIM_STD_GO_SOUTH]         = sMonAnim_GoSouth,
    [ANIM_STD_GO_NORTH]         = sMonAnim_GoNorth,
    [ANIM_STD_GO_WEST]          = sMonAnim_GoWest,
    [ANIM_STD_GO_EAST]          = sMonAnim_GoEast,
    [ANIM_STD_GO_FAST_SOUTH]    = sMonAnim_GoFastSouth,
    [ANIM_STD_GO_FAST_NORTH]    = sMonAnim_GoFastNorth,
    [ANIM_STD_GO_FAST_WEST]     = sMonAnim_GoFastWest,
    [ANIM_STD_GO_FAST_EAST]     = sMonAnim_GoFastEast,
    [ANIM_STD_GO_FASTER_SOUTH]  = sMonAnim_GoFasterSouth,
    [ANIM_STD_GO_FASTER_NORTH]  = sMonAnim_GoFasterNorth,
    [ANIM_STD_GO_FASTER_WEST]   = sMonAnim_GoFasterWest,
    [ANIM_STD_GO_FASTER_EAST]   = sMonAnim_GoFasterEast,
    [ANIM_STD_GO_FASTEST_SOUTH] = sMonAnim_GoFastestSouth,
    [ANIM_STD_GO_FASTEST_NORTH] = sMonAnim_GoFastestNorth,
    [ANIM_STD_GO_FASTEST_WEST]  = sMonAnim_GoFastestWest,
    [ANIM_STD_GO_FASTEST_EAST]  = sMonAnim_GoFastestEast,
    [ANIM_RAISE_HAND]           = sMonAnim_FaceSouth,
};

