#include "defines.h"
#include "../include/follower_mon.h"
#include "../include/follower_mon_sprites.h"
#include "../include/pokemon.h"
#include "../include/new/follow_me.h"
#include "../include/global.fieldmap.h"
#include "../include/event_object_movement.h"
#include "../include/script_menu.h"
#include "../include/new_menu_helpers.h"
#include "../include/script.h"
#include "../include/follower_mon_pal.h"
#include "../include/new/character_customization.h"


extern u8 SparkleTiles[];
extern u16 SparklePal[];

static void SpriteCB_Sparkle(struct Sprite *sprite);

static const struct OamData sSparkleOamData =
{
    .y = 0,
    .affineMode = ST_OAM_AFFINE_NORMAL,
    .objMode = ST_OAM_OBJ_NORMAL,
    .mosaic = 0,
    .bpp = ST_OAM_4BPP,
    .shape = ST_OAM_SQUARE,
    .x = 0,
    .matrixNum = 0,
    .size = ST_OAM_SIZE_2,
    .tileNum = 0,
    .priority = 0,
    .paletteNum = 0,
    .affineParam = 0,
};

static const union AnimCmd sSparkleAnim0[] =
{
    ANIMCMD_FRAME(0, 5),
    ANIMCMD_FRAME(16, 5),
    ANIMCMD_FRAME(32, 5),
    ANIMCMD_FRAME(48, 5),
    ANIMCMD_FRAME(64, 5),
    ANIMCMD_FRAME(80, 5),
    ANIMCMD_END,
};

static const union AffineAnimCmd sSparkleAffineAnim0[] =
{
    AFFINEANIMCMD_FRAME(256, 256, 0, 0),
    AFFINEANIMCMD_FRAME(4, 4, 8, 30),
    AFFINEANIMCMD_END,
};

static const union AnimCmd *const sSparkleAnimTable[] =
{
    sSparkleAnim0,
};

static const union AffineAnimCmd *const sSparkleAffineAnimTable[] =
{
    sSparkleAffineAnim0,
};

static struct SpriteSheet sSparkleTileData =
{
    .data = SparkleTiles,
    .size = (192 * 32) / 2,
    .tag = 12,
};

static struct SpritePalette sSparklePalData =
{
    .data = SparklePal,
    .tag = 12,
};

static struct SpriteTemplate sSparkleTemplate =
{
    .tileTag = 12,
    .paletteTag = 12,
    .oam = &sSparkleOamData,
    .anims = sSparkleAnimTable,
    .images = NULL,
    .affineAnims = sSparkleAffineAnimTable,
    .callback = SpriteCB_Sparkle,
};

static void SpriteCB_Sparkle(struct Sprite *sprite)
{
    if (sprite->data[0] == 30)
        DestroySprite(sprite);
    else
        sprite->data[0]++;
}

void CreateSparkleSprite(void)
{
    if (FlagGet(FLAG_FOLLOWER_POKEMON) && gFollowerState.inProgress)
    {
        struct Sprite *followerSprite = &gSprites[gEventObjects[gFollowerState.objId].spriteId];
        s16 posX = followerSprite->pos1.x - 16;
        s16 posY = followerSprite->pos1.y - 10;
        u8 spriteId;

        LoadSpriteSheet(&sSparkleTileData);
        LoadSpritePalette(&sSparklePalData);
        spriteId = CreateSprite(&sSparkleTemplate, posX, posY, 0);

        gSprites[spriteId].data[0] = 0;
        gSprites[spriteId].centerToCornerVecX = 0;
        gSprites[spriteId].centerToCornerVecY = 0;
        gSprites[spriteId].coordOffsetEnabled = TRUE;
    }
}

u16 GetFollowerMonSprite(void)
{
    struct Pokemon *mon = GetFirstValidPartyMon();
    if (mon == NULL)
        return 0;

    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    return gFollowerMonSpriteIdTable[species] + 256;
}

bool8 HasLeadFollowerMon(void)
{
    return GetFirstValidPartyMon() != NULL;
}

void CreateFollowerMonObject(void)
{
    u16 sprite = GetFollowerMonSprite();
    if (sprite == 0)  // If there is no valid Pokémon, do not create the follower
        return;
    struct EventObject *playerObj = &gEventObjects[gPlayerAvatar->eventObjectId];
 
         s16 posX = playerObj->currentCoords.x - 7;
         s16 posY = playerObj->currentCoords.y - 7;
     
         // Adjusts follower position based on player direction
         switch (playerObj->facingDirection)
    {
        case DIR_SOUTH: posY -= 1; break;
         case DIR_NORTH: posY += 1; break;
         case DIR_WEST:  posX += 1; break;
         case DIR_EAST:  posX -= 1; break;
     }
 
     // Check if follower already exists before creating a new one
     for (u8 i = 0; i < MAP_OBJECTS_COUNT; i++)
     {
         if (gEventObjects[i].localId == DEFAULT_FOLLOWER_LOCAL_ID && gEventObjects[i].active)
             return;  // There is already a follower, so don't create another one
    }

    struct EventObjectTemplate followerObj =
    {
        .localId = DEFAULT_FOLLOWER_LOCAL_ID,
        .graphicsIdLowerByte = sprite & 0xFF,
        .graphicsIdUpperByte = sprite >> 8,
        .x = posX,
        .y = posY,
        .elevation = 3,
        .movementType = 1,
        .movementRangeX = 0,
        .movementRangeY = 0,
        .trainerType = 0,
        .trainerRange_berryTreeId = 0,
    };

    SpawnSpecialEventObject(&followerObj);
}

void FollowerMonFacePlayer(void)
{
    u8 dir;

    switch (gEventObjects[gPlayerAvatar->eventObjectId].facingDirection)
    {
        case DIR_SOUTH:
            dir = DIR_NORTH;
            break;
        case DIR_NORTH:
            dir = DIR_SOUTH;
            break;
        case DIR_WEST:
            dir = DIR_EAST;
            break;
        case DIR_EAST:
            dir = DIR_WEST;
            break;
        case DIR_SOUTHWEST:
            dir = DIR_SOUTHEAST;
            break;
        case DIR_SOUTHEAST:
            dir = DIR_SOUTHWEST;
            break;
        case DIR_NORTHWEST:
            dir = DIR_NORTHEAST;
            break;
        case DIR_NORTHEAST:
            dir = DIR_NORTHWEST;
            break;
        default:
            dir = DIR_NORTH;
            break;
    }

    EventObjectTurn(&gEventObjects[gFollowerState.objId], dir);
}

void TurnFollowerMonToPlayer(void)
{
    u8 dir = gEventObjects[gPlayerAvatar->eventObjectId].facingDirection;
    EventObjectTurn(&gEventObjects[gFollowerState.objId], dir);
}

void ShowFollowerMon(void)
{
    if (FlagGet(FLAG_FOLLOWER_POKEMON) && gFollowerState.inProgress)
        gEventObjects[gFollowerState.objId].invisible = FALSE;
}
extern void Task_ScriptShowMonPic(u8 taskId);
#define gMonPaletteTable (*((struct CompressedSpritePalette**) 0x8000130))
#define gMonShinyPaletteTable (*((struct CompressedSpritePalette**) 0x8000134))

struct CompressedSpritePalette * GetSpritePalToUse(bool8 isShiny)
{
    if(isShiny)
        return gMonShinyPaletteTable;
    else
        return gMonPaletteTable;
}

u8 CreateMonSprite_MysteryGift(u16 species, s16 x, s16 y)
{
    struct Pokemon* mon = GetFirstValidPartyMon();
    if (mon == NULL || species == SPECIES_NONE || species >= NUM_SPECIES)
        return MAX_SPRITES;

    u32 personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    u32 otId = GetMonData(mon, MON_DATA_OT_ID, NULL);
    u16 isShiny = IsMonShiny(mon);
    const struct CompressedSpritePalette * spritePal = GetSpritePalToUse(isShiny);
    u16 spriteId = CreateMonPicSprite_HandleDeoxys(species, otId, personality, 1, x, y, 0, spritePal[species].tag);
    LoadCompressedSpritePalette(&spritePal[species]);
    if(spriteId != 0xFFFF)
    {
        gSprites[spriteId].oam.paletteNum = IndexOfSpritePaletteTag(spritePal[species].tag);
    }
    if (spriteId == 0xFFFF)
        return MAX_SPRITES;
    else
        return spriteId;
}

bool8 ScriptMenu_ShowMysteryPokemonPic(u16 species, u8 x, u8 y)
{
    u8 spriteId;
    u8 taskId;
    if (FindTaskIdByFunc(Task_ScriptShowMonPic) != 0xFF)
        return FALSE;
    spriteId = CreateMonSprite_MysteryGift(species, 8 * x + 40, 8 * y + 40);
    if (spriteId >= MAX_SPRITES)
        return FALSE;

    taskId = CreateTask(Task_ScriptShowMonPic, 80);
    gTasks[taskId].data[0] = 0;
    gTasks[taskId].data[1] = species;
    gTasks[taskId].data[2] = spriteId;
    gSprites[spriteId].callback = SpriteCallbackDummy;
    gSprites[spriteId].oam.priority = 0;
    SetStandardWindowBorderStyle(gTasks[taskId].data[5], TRUE);
    ScheduleBgCopyTilemapToVram(0);
    return TRUE;
}

bool8 ShowMysteryGiftMon()
{
    u16 species = Var8004;
    u8 x = 0x1A;
    u8 y = 0x2;

    ScriptMenu_ShowMysteryPokemonPic(species, x, y);
    return FALSE;
}
#define tState        data[0]
#define tSpecies      data[1]
#define tSpriteId     data[2]
#define tWindowId     data[5]
void Remove_PokemonPic(void)
{
    u8 taskId = FindTaskIdByFunc(Task_ScriptShowMonPic);
    
    if (taskId != 0xFF)
    {
        u8 spriteId = gTasks[taskId].tSpriteId;

        if (spriteId < MAX_SPRITES)
        {
            struct Sprite *sprite = &gSprites[spriteId];

            FreeSpriteOamMatrix(sprite);
            DestroySprite(sprite);
            FreeSpriteTiles(sprite);
            FreeSpritePalette(sprite);
        }
        DestroyTask(taskId);
    }
}

struct Pokemon* GetFirstValidPartyMon(void)
{
    for (u8 i = 0; i < PARTY_SIZE; ++i)
    {
        struct Pokemon *mon = &gPlayerParty[i];
        if (GetMonData(mon, MON_DATA_SPECIES, NULL) != SPECIES_NONE
         && !GetMonData(mon, MON_DATA_IS_EGG, NULL)
         && GetMonData(mon, MON_DATA_HP, NULL) > 0)
            return mon;
    }

    return NULL;
}

void SetFollowerMonSpeciesVar(void)
{
    struct Pokemon *mon = GetFirstValidPartyMon();
    Var8004 = mon == NULL ? SPECIES_NONE : GetMonData(mon, MON_DATA_SPECIES, NULL);
}

static u8 GetFollowerMapObjId(void)
{
	return gFollowerState.objId;
}

static const u16 sSpeciesToPaletteTag[] =
{
    [SPECIES_BULBORBLARVA] = OBJ_EVENT_PAL_TAG_BULBORBLARVA_SHINY,
    [SPECIES_BULBORB] = OBJ_EVENT_PAL_TAG_BULBORB_SHINY,
    [SPECIES_JUMBOBULBORB] = OBJ_EVENT_PAL_TAG_JUMBOBULBORB_SHINY,
    [SPECIES_FIERYBLOWLET] = OBJ_EVENT_PAL_TAG_FIERYBLOWLET_SHINY,
    [SPECIES_FIERYBLOWHOG] = OBJ_EVENT_PAL_TAG_FIERYBLOWHOG_SHINY,
    [SPECIES_TITANBLOWHOG] = OBJ_EVENT_PAL_TAG_TITANBLOWHOG_SHINY,
    [SPECIES_WOLPOLE] = OBJ_EVENT_PAL_TAG_WOLPOLE_SHINY,
    [SPECIES_YELLOWWOLLYHOP] = OBJ_EVENT_PAL_TAG_YELLOWWOLLYHOP_SHINY,
    [SPECIES_MASTERHOP] = OBJ_EVENT_PAL_TAG_MASTERHOP_SHINY,
	[SPECIES_FLINTBEETLE] 		= OBJ_EVENT_PAL_TAG_FLINTBEETLE_SHINY,
	[SPECIES_DOODLEBUG] 		= OBJ_EVENT_PAL_TAG_DOODLEBUG_SHINY,
	[SPECIES_GLINTBEETLE] 		= OBJ_EVENT_PAL_TAG_GLINTBEETLE_SHINY,
	[SPECIES_SWOOPINGSNITCHBUG] 	= OBJ_EVENT_PAL_TAG_SWOOPINGSNITCHBUG_SHINY,
	[SPECIES_BUMBLINGSNITCHBUG] 	= OBJ_EVENT_PAL_TAG_BUMBLINGSNITCHBUG_SHINY,
	[SPECIES_DIRIGIBUG] 		= OBJ_EVENT_PAL_TAG_DIRIGIBUG_SHINY,
	[SPECIES_SNOWBULBORB] 		= OBJ_EVENT_PAL_TAG_SNOWBULBORB_SHINY,
	[SPECIES_DWARFFROSTYBULBORB] 	= OBJ_EVENT_PAL_TAG_DWARFFROSTYBULBORB_SHINY,
	[SPECIES_FROSTYBULBORB] 		= OBJ_EVENT_PAL_TAG_FROSTYBULBORB_SHINY,
	[SPECIES_CRUMBUG] 			= OBJ_EVENT_PAL_TAG_CRUMBUG_SHINY,
	[SPECIES_BREADBUG] 			= OBJ_EVENT_PAL_TAG_BREADBUG_SHINY,
	[SPECIES_GIANTBREADBUG] 		= OBJ_EVENT_PAL_TAG_GIANTBREADBUG_SHINY,
	[SPECIES_EMPERORBULBLAX] 		= OBJ_EVENT_PAL_TAG_EMPERORBULBLAX_SHINY,
	[SPECIES_SOVREIGNBULBLAX] 		= OBJ_EVENT_PAL_TAG_SOVREIGNBULBLAX_SHINY,
	[SPECIES_DWARFBULBEAR] 		= OBJ_EVENT_PAL_TAG_DWARFBULBEAR_SHINY,
	[SPECIES_SPOTTYBULBEAR] 		= OBJ_EVENT_PAL_TAG_SPOTTYBULBEAR_SHINY,
	[SPECIES_HONEYWISP] 		= OBJ_EVENT_PAL_TAG_HONEYWISP_SHINY,
	[SPECIES_DANDELFLY] 		= OBJ_EVENT_PAL_TAG_DANDELFLY_SHINY,
	[SPECIES_DOWNYSNAGRET] 		= OBJ_EVENT_PAL_TAG_DOWNYSNAGRET_SHINY,
	[SPECIES_BURROWINGSNAGRET] 		= OBJ_EVENT_PAL_TAG_BURROWINGSNAGRET_SHINY,
	[SPECIES_PILEATEDSNAGRET] 		= OBJ_EVENT_PAL_TAG_PILEATEDSNAGRET_SHINY,
	[SPECIES_FEMALESHEARGRUB] 		= OBJ_EVENT_PAL_TAG_FEMALESHEARGRUB_SHINY,
	[SPECIES_SWARMINGSHEARGRUB] 	= OBJ_EVENT_PAL_TAG_SWARMINGSHEARGRUB_SHINY,
	[SPECIES_MAMASHEARGRUB] 		= OBJ_EVENT_PAL_TAG_MAMASHEARGRUB_SHINY,
	[SPECIES_MALESHEARGRUB] 		= OBJ_EVENT_PAL_TAG_MALESHEARGRUB_SHINY,
	[SPECIES_SHEARWIG] 			= OBJ_EVENT_PAL_TAG_SHEARWIG_SHINY,
	[SPECIES_QUEENSHEARWIG] 		= OBJ_EVENT_PAL_TAG_QUEENSHEARWIG_SHINY,
	[SPECIES_ARISTOCRABOFFSPRING] 	= OBJ_EVENT_PAL_TAG_ARISTOCRABOFFSPRING_SHINY,
	[SPECIES_ARISTOCRAB] 		= OBJ_EVENT_PAL_TAG_ARISTOCRAB_SHINY,
	[SPECIES_GOOLIX] 			= OBJ_EVENT_PAL_TAG_GOOLIX_SHINY,
	[SPECIES_FOOLIX] 			= OBJ_EVENT_PAL_TAG_FOOLIX_SHINY,
	[SPECIES_ARCTICCANNONLARVA] 	= OBJ_EVENT_PAL_TAG_ARCTICCANNONLARVA_SHINY,
	[SPECIES_ARCTICCANNONBEETLE] 	= OBJ_EVENT_PAL_TAG_ARCTICCANNONBEETLE_SHINY,
	[SPECIES_SKITTERLEAF] 		= OBJ_EVENT_PAL_TAG_SKITTERLEAF_SHINY,
	[SPECIES_DESICCATEDSKITTERLEAF] 	= OBJ_EVENT_PAL_TAG_DESICCATEDSKITTERLEAF_SHINY,
	[SPECIES_ARMOREDCANNONLARVA] 	= OBJ_EVENT_PAL_TAG_ARMOREDCANNONLARVA_SHINY,
	[SPECIES_ARMOREDCANNONBEETLE] 	= OBJ_EVENT_PAL_TAG_ARMOREDCANNONBEETLE_SHINY,
	[SPECIES_HORNEDCANNONBEETLE] 	= OBJ_EVENT_PAL_TAG_HORNEDCANNONBEETLE_SHINY,
	[SPECIES_CREEPINGCHRYSANTHEMUM] 	= OBJ_EVENT_PAL_TAG_CREEPINGCHRYSANTHEMUM_SHINY,
	[SPECIES_STARTLESPORE] 		= OBJ_EVENT_PAL_TAG_STARTLESPORE_SHINY,
	[SPECIES_HERMITCRAWMAD] 		= OBJ_EVENT_PAL_TAG_HERMITCRAWMAD_SHINY,
	[SPECIES_BUGEYEDCRAWMAD] 		= OBJ_EVENT_PAL_TAG_BUGEYEDCRAWMAD_SHINY,
	[SPECIES_DWARFBULBORB] 		= OBJ_EVENT_PAL_TAG_DWARFBULBORB_SHINY,
	[SPECIES_DWARFORANGEBULBORB] 	= OBJ_EVENT_PAL_TAG_DWARFORANGEBULBORB_SHINY,
	[SPECIES_BEADYLONGLEGS] 		= OBJ_EVENT_PAL_TAG_BEADYLONGLEGS_SHINY,
	[SPECIES_RAGINGLONGLEGS] 		= OBJ_EVENT_PAL_TAG_RAGINGLONGLEGS_SHINY,
	[SPECIES_BALDYLONGLEGS] 		= OBJ_EVENT_PAL_TAG_BALDYLONGLEGS_SHINY,
	[SPECIES_SHAGGYLONGLEGS] 		= OBJ_EVENT_PAL_TAG_SHAGGYLONGLEGS_SHINY,
	[SPECIES_BULBMIN] 			= OBJ_EVENT_PAL_TAG_BULBMIN_SHINY,
	[SPECIES_ADULTBULBMIN] 		= OBJ_EVENT_PAL_TAG_ADULTBULBMIN_SHINY,
	[SPECIES_SCORNET] 			= OBJ_EVENT_PAL_TAG_SCORNET_SHINY,
	[SPECIES_SCORNETMAESTRO] 		= OBJ_EVENT_PAL_TAG_SCORNETMAESTRO_SHINY,
	[SPECIES_BURROWNIT] 		= OBJ_EVENT_PAL_TAG_BURROWNIT_SHINY,
	[SPECIES_JOUSTMITE] 		= OBJ_EVENT_PAL_TAG_JOUSTMITE_SHINY,
	[SPECIES_FLIGHTYJOUSTMITE] 		= OBJ_EVENT_PAL_TAG_FLIGHTYJOUSTMITE_SHINY,
	[SPECIES_VOLATILEDWEEVIL] 		= OBJ_EVENT_PAL_TAG_VOLATILEDWEEVIL_SHINY,
	[SPECIES_MANATLEGS] 		= OBJ_EVENT_PAL_TAG_MANATLEGS_SHINY,
	[SPECIES_SKUTTERCHUCK] 		= OBJ_EVENT_PAL_TAG_SKUTTERCHUCK_SHINY,
	[SPECIES_CALCIFIEDCRUSHBLAT] 	= OBJ_EVENT_PAL_TAG_CALCIFIEDCRUSHBLAT_SHINY,
	[SPECIES_ARACHNODE] 		= OBJ_EVENT_PAL_TAG_ARACHNODE_SHINY,
	[SPECIES_MOLDYDWARFBULBORB] 	= OBJ_EVENT_PAL_TAG_MOLDYDWARFBULBORB_SHINY,
	[SPECIES_MOLDYSLOOCH] 		= OBJ_EVENT_PAL_TAG_MOLDYSLOOCH_SHINY,
	[SPECIES_TOXSTOOL] 			= OBJ_EVENT_PAL_TAG_TOXSTOOL_SHINY,
	[SPECIES_PHOSBAT] 			= OBJ_EVENT_PAL_TAG_PHOSBAT_SHINY,
	[SPECIES_VEHEAMOTHPHOSBAT] 		= OBJ_EVENT_PAL_TAG_VEHEAMOTHPHOSBAT_SHINY,
	[SPECIES_PUCKERINGBLINNOW] 		= OBJ_EVENT_PAL_TAG_PUCKERINGBLINNOW_SHINY,
	[SPECIES_SPUTTLEFISH] 		= OBJ_EVENT_PAL_TAG_SPUTTLEFISH_SHINY,
	[SPECIES_PRICKLEPUFF] 		= OBJ_EVENT_PAL_TAG_PRICKLEPUFF_SHINY,
	[SPECIES_UJADANI] 			= OBJ_EVENT_PAL_TAG_UJADANI_SHINY,
	[SPECIES_MITITE] 			= OBJ_EVENT_PAL_TAG_MITITE_SHINY,
	[SPECIES_WITHERINGBLOWHOG] 		= OBJ_EVENT_PAL_TAG_WITHERINGBLOWHOG_SHINY,
	[SPECIES_PUFFYBLOWHOG] 		= OBJ_EVENT_PAL_TAG_PUFFYBLOWHOG_SHINY,
	[SPECIES_MINIATURESNOOTWHACKER] 	= OBJ_EVENT_PAL_TAG_MINIATURESNOOTWHACKER_SHINY,
	[SPECIES_MAMMOTHSNOOTWHACKER] 	= OBJ_EVENT_PAL_TAG_MAMMOTHSNOOTWHACKER_SHINY,
	[SPECIES_PYROCLASTICSLOOCH] 	= OBJ_EVENT_PAL_TAG_PYROCLASTICSLOOCH_SHINY,
	[SPECIES_LESSERSPOTTEDJELLYFLOAT] 	= OBJ_EVENT_PAL_TAG_LESSERSPOTTEDJELLYFLOAT_SHINY,
	[SPECIES_GREATERSPOTTEDJELLYFLOAT] 	= OBJ_EVENT_PAL_TAG_GREATERSPOTTEDJELLYFLOAT_SHINY,
	[SPECIES_TOADYBLOYSTER] 		= OBJ_EVENT_PAL_TAG_TOADYBLOYSTER_SHINY,
	[SPECIES_RANGINGBLOYSTER] 		= OBJ_EVENT_PAL_TAG_RANGINGBLOYSTER_SHINY,
	[SPECIES_SNOWYBLOWHOG] 		= OBJ_EVENT_PAL_TAG_SNOWYBLOWHOG_SHINY,
	[SPECIES_BLIZZARDINGBLOWHOG] 	= OBJ_EVENT_PAL_TAG_BLIZZARDINGBLOWHOG_SHINY,
	[SPECIES_GILDEMANDWEE] 		= OBJ_EVENT_PAL_TAG_GILDEMANDWEE_SHINY,
	[SPECIES_GILDEMANDER] 		= OBJ_EVENT_PAL_TAG_GILDEMANDER_SHINY,
	[SPECIES_WADDLEQUAFF] 		= OBJ_EVENT_PAL_TAG_WADDLEQUAFF_SHINY,
	[SPECIES_GRUBCHUCKER] 		= OBJ_EVENT_PAL_TAG_GRUBCHUCKER_SHINY,
	[SPECIES_PEARLYCLAMCLAMP] 		= OBJ_EVENT_PAL_TAG_PEARLYCLAMCLAMP_SHINY,
	[SPECIES_SUNQUISH] 			= OBJ_EVENT_PAL_TAG_SUNQUISH_SHINY,
	[SPECIES_PROQUILLION] 		= OBJ_EVENT_PAL_TAG_PROQUILLION_SHINY,
	[SPECIES_TUSKEDBLOWHOG] 		= OBJ_EVENT_PAL_TAG_TUSKEDBLOWHOG_SHINY,
	[SPECIES_SNOWFLAKEFLUTTERTAIL] 	= OBJ_EVENT_PAL_TAG_SNOWFLAKEFLUTTERTAIL_SHINY,
	[SPECIES_BOGSWALLOW] 		= OBJ_EVENT_PAL_TAG_BOGSWALLOW_SHINY,
	[SPECIES_PUFFMIN] 			= OBJ_EVENT_PAL_TAG_PUFFMIN_SHINY,
	[SPECIES_WOLLYHOP] 			= OBJ_EVENT_PAL_TAG_WOLLYHOP_SHINY,
	[SPECIES_CHILLYHOP] 		= OBJ_EVENT_PAL_TAG_CHILLYHOP_SHINY,
	[SPECIES_BLOOMCAPBLOYSTER] 		= OBJ_EVENT_PAL_TAG_BLOOMCAPBLOYSTER_SHINY,
	[SPECIES_SCORCHCAKE] 		= OBJ_EVENT_PAL_TAG_SCORCHCAKE_SHINY,
	[SPECIES_WATERDUMPLE] 		= OBJ_EVENT_PAL_TAG_WATERDUMPLE_SHINY,
	[SPECIES_LONGWATERDUMPLE] 		= OBJ_EVENT_PAL_TAG_LONGWATERDUMPLE_SHINY,
	[SPECIES_MOCKIWI] 			= OBJ_EVENT_PAL_TAG_MOCKIWI_SHINY,
	[SPECIES_CRESTEDMOCKIWI] 		= OBJ_EVENT_PAL_TAG_CRESTEDMOCKIWI_SHINY,
	[SPECIES_ELONGATEDCRUSHBLAT] 	= OBJ_EVENT_PAL_TAG_ELONGATEDCRUSHBLAT_SHINY,
	[SPECIES_PUFFSTALK] 		= OBJ_EVENT_PAL_TAG_PUFFSTALK_SHINY,
	[SPECIES_PUFFSTOOL] 		= OBJ_EVENT_PAL_TAG_PUFFSTOOL_SHINY,
	[SPECIES_ANODEBEETLE] 		= OBJ_EVENT_PAL_TAG_ANODEBEETLE_SHINY,
	[SPECIES_EMPRESSBULBLAX] 		= OBJ_EVENT_PAL_TAG_EMPRESSBULBLAX_SHINY,
	[SPECIES_SKEETERSKATE] 		= OBJ_EVENT_PAL_TAG_SKEETERSKATE_SHINY,
	[SPECIES_MUCKERSKATE] 		= OBJ_EVENT_PAL_TAG_MUCKERSKATE_SHINY,
	[SPECIES_GROOVYLONGLEGS] 		= OBJ_EVENT_PAL_TAG_GROOVYLONGLEGS_SHINY,
	[SPECIES_CRUSTEDRUMPUP] 		= OBJ_EVENT_PAL_TAG_CRUSTEDRUMPUP_SHINY,
	[SPECIES_BEARDEDAMPRAT] 		= OBJ_EVENT_PAL_TAG_BEARDEDAMPRAT_SHINY,
	[SPECIES_FIERYBULBLAX] 		= OBJ_EVENT_PAL_TAG_FIERYBULBLAX_SHINY,
	[SPECIES_GATTLINGGROINK] 		= OBJ_EVENT_PAL_TAG_GATTLINGGROINK_SHINY,
	[SPECIES_ARMURK] 			= OBJ_EVENT_PAL_TAG_ARMURK_SHINY,
	[SPECIES_SEGMENTEDCRAWBSTER] 	= OBJ_EVENT_PAL_TAG_SEGMENTEDCRAWBSTER_SHINY,
	[SPECIES_ARMOREDMAWDAD] 		= OBJ_EVENT_PAL_TAG_ARMOREDMAWDAD_SHINY,
	[SPECIES_SANDBELCHINGMEERSLUG] 	= OBJ_EVENT_PAL_TAG_SANDBELCHINGMEERSLUG_SHINY,
	[SPECIES_CLICKINGSLURKER] 		= OBJ_EVENT_PAL_TAG_CLICKINGSLURKER_SHINY,
	[SPECIES_LURINGSLURKER] 		= OBJ_EVENT_PAL_TAG_LURINGSLURKER_SHINY,
	[SPECIES_MEDUSALSLURKER] 		= OBJ_EVENT_PAL_TAG_MEDUSALSLURKER_SHINY,
	[SPECIES_PELLETPOSY] 		= OBJ_EVENT_PAL_TAG_PELLETPOSY_SHINY,
	[SPECIES_MASTERONION] 		= OBJ_EVENT_PAL_TAG_MASTERONION_SHINY,
	[SPECIES_OATCHI] 			= OBJ_EVENT_PAL_TAG_OATCHI_SHINY,
	[SPECIES_QUAGGLEDMIRECLOPS] 	= OBJ_EVENT_PAL_TAG_QUAGGLEDMIRECLOPS_SHINY,
	[SPECIES_ALBINODWARFBULBORB] 	= OBJ_EVENT_PAL_TAG_ALBINODWARFBULBORB_SHINY,
	[SPECIES_HAIRYBULBORB] 		= OBJ_EVENT_PAL_TAG_HAIRYBULBORB_SHINY,
	[SPECIES_WHIPTONGUEBULBORB] 	= OBJ_EVENT_PAL_TAG_WHIPTONGUEBULBORB_SHINY,
	[SPECIES_ORANGEBULBORB] 		= OBJ_EVENT_PAL_TAG_ORANGEBULBORB_SHINY,
	[SPECIES_WHITEPIKMIN] 		= OBJ_EVENT_PAL_TAG_WHITEPIKMIN_SHINY,
	[SPECIES_BLUEPIKMIN] 		= OBJ_EVENT_PAL_TAG_BLUEPIKMIN_SHINY,
	[SPECIES_ROCKPIKMIN] 		= OBJ_EVENT_PAL_TAG_ROCKPIKMIN_SHINY,
	[SPECIES_YELLOWPIKMIN] 		= OBJ_EVENT_PAL_TAG_YELLOWPIKMIN_SHINY,
	[SPECIES_WINGEDPIKMIN] 		= OBJ_EVENT_PAL_TAG_WINGEDPIKMIN_SHINY,
	[SPECIES_REDPIKMIN] 		= OBJ_EVENT_PAL_TAG_REDPIKMIN_SHINY,
	[SPECIES_PURPLEPIKMIN] 		= OBJ_EVENT_PAL_TAG_PURPLEPIKMIN_SHINY,
	[SPECIES_WATERWRAITH] 		= OBJ_EVENT_PAL_TAG_WATERWRAITH_SHINY,
	[SPECIES_TITANDWEEVIL] 		= OBJ_EVENT_PAL_TAG_TITANDWEEVIL_SHINY,
	[SPECIES_PLASMWRAITH] 		= OBJ_EVENT_PAL_TAG_PLASMWRAITH_SHINY,
	[SPECIES_ICEPIKMIN] 		= OBJ_EVENT_PAL_TAG_ICEPIKMIN_SHINY,
	[SPECIES_GLOWSEED] 			= OBJ_EVENT_PAL_TAG_GLOWSEED_SHINY,
	[SPECIES_GLOWPIKMIN] 		= OBJ_EVENT_PAL_TAG_GLOWPIKMIN_SHINY,
	[SPECIES_SMOKYPROGG] 		= OBJ_EVENT_PAL_TAG_SMOKYPROGG_SHINY,
	[SPECIES_MAMUTA] 			= OBJ_EVENT_PAL_TAG_MAMUTA_SHINY,
	[SPECIES_MOSS] 			= OBJ_EVENT_PAL_TAG_MOSS_SHINY,
	[SPECIES_TOYBORB] 			= OBJ_EVENT_PAL_TAG_TOYBORB_SHINY,
	[SPECIES_BULBLORD] 			= OBJ_EVENT_PAL_TAG_BULBLORD_SHINY,
	[SPECIES_PINCHIPEDE] 		= OBJ_EVENT_PAL_TAG_PINCHIPEDE_SHINY,
	[SPECIES_LARGEMOUTHWOLLYHOP] 	= OBJ_EVENT_PAL_TAG_LARGEMOUTHWOLLYHOP_SHINY,
	[SPECIES_TOYBLOWHOG] 		= OBJ_EVENT_PAL_TAG_TOYBLOWHOG_SHINY,
	[SPECIES_TELESCOPINGPUMPHOG] 	= OBJ_EVENT_PAL_TAG_TELESCOPINGPUMPHOG_SHINY,
	[SPECIES_BEEB] 			= OBJ_EVENT_PAL_TAG_BEEB_SHINY,
	[SPECIES_BLADEDBEEB] 		= OBJ_EVENT_PAL_TAG_BLADEDBEEB_SHINY,
	[SPECIES_STUDDEDBEEB] 		= OBJ_EVENT_PAL_TAG_STUDDEDBEEB_SHINY,
	[SPECIES_FIREFLAPBULBORB] 		= OBJ_EVENT_PAL_TAG_FIREFLAPBULBORB_SHINY,
	[SPECIES_ICEBLOWNDWEEVIL] 		= OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_SHINY,
	[SPECIES_SPECTRALID] 		= OBJ_EVENT_PAL_TAG_SPECTRALID_SHINY,
	[SPECIES_BLUBBUG] 			= OBJ_EVENT_PAL_TAG_BLUBBUG_SHINY,
	[SPECIES_PUFFYBLUBBUG] 		= OBJ_EVENT_PAL_TAG_PUFFYBLUBBUG_SHINY,
	[SPECIES_STUFFEDBELLBLOOM] 		= OBJ_EVENT_PAL_TAG_STUFFEDBELLBLOOM_SHINY,
	[SPECIES_CENTIPARE] 		= OBJ_EVENT_PAL_TAG_CENTIPARE_SHINY,
	[SPECIES_ADULTCENTIPARE] 		= OBJ_EVENT_PAL_TAG_ADULTCENTIPARE_SHINY,
	[SPECIES_WATERYBLOWHOG] 		= OBJ_EVENT_PAL_TAG_WATERYBLOWHOG_SHINY,
	[SPECIES_GRABBIT] 			= OBJ_EVENT_PAL_TAG_GRABBIT_SHINY,
	[SPECIES_COPPELLER] 		= OBJ_EVENT_PAL_TAG_COPPELLER_SHINY,
	[SPECIES_MUGGONFLY] 		= OBJ_EVENT_PAL_TAG_MUGGONFLY_SHINY,
	[SPECIES_ELECTRICCOTTONADE] 	= OBJ_EVENT_PAL_TAG_ELECTRICCOTTONADE_SHINY,
	[SPECIES_WADDLEPUS] 		= OBJ_EVENT_PAL_TAG_WADDLEPUS_SHINY,
	[SPECIES_CRAMMEDWRAITH] 		= OBJ_EVENT_PAL_TAG_CRAMMEDWRAITH_SHINY,
	[SPECIES_BERSERKLEECHHYDROE] 	= OBJ_EVENT_PAL_TAG_BERSERKLEECHHYDROE_SHINY,
	[SPECIES_PEBBLEPITCHER] 		= OBJ_EVENT_PAL_TAG_PEBBLEPITCHER_SHINY,
	[SPECIES_ANCIENTSIREHOUND] 		= OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_SHINY,
	[SPECIES_COURAGEREACTOR] 		= OBJ_EVENT_PAL_TAG_COURAGEREACTOR_SHINY,
	[SPECIES_ASSEMBLEDCOURAGE] 		= OBJ_EVENT_PAL_TAG_ASSEMBLEDCOURAGE_SHINY,
	[SPECIES_REMEMBEREDOLDBUDDY] 	= OBJ_EVENT_PAL_TAG_REMEMBEREDOLDBUDDY_SHINY,
	[SPECIES_BULBORBWITHAGUN] 		= OBJ_EVENT_PAL_TAG_BULBORBWITHAGUN_SHINY,
	[SPECIES_KIRBY] 			= OBJ_EVENT_PAL_TAG_KIRBY_SHINY,
	[SPECIES_SOUL] 			= OBJ_EVENT_PAL_TAG_SOUL_SHINY,
	[SPECIES_PLACEHOLDERLARVA] 		= OBJ_EVENT_PAL_TAG_PLACEHOLDERLARVA_SHINY,
	[SPECIES_DEMO77] 			= OBJ_EVENT_PAL_TAG_DEMO77_SHINY,
	[SPECIES_USUBA] 			= OBJ_EVENT_PAL_TAG_USUBA_SHINY,
	[SPECIES_KAKUREIMO] 		= OBJ_EVENT_PAL_TAG_KAKUREIMO_SHINY,
	[SPECIES_PIKUTABE] 			= OBJ_EVENT_PAL_TAG_PIKUTABE_SHINY,
	[SPECIES_NAMAPONGASHI] 		= OBJ_EVENT_PAL_TAG_NAMAPONGASHI_SHINY,
	[SPECIES_CHAPPYPROTO] 		= OBJ_EVENT_PAL_TAG_CHAPPYPROTO_SHINY,

	[SPECIES_EGG] 			= OBJ_EVENT_PAL_TAG_EGG_SHINY,

	[SPECIES_GILDEMANDWEE_NOGOLD] 	= OBJ_EVENT_PAL_TAG_GILDEMANDWEE_SHINY,
	[SPECIES_GILDEMANDER_NOGOLD] 	= OBJ_EVENT_PAL_TAG_GILDEMANDER_SHINY,
	[SPECIES_BEARDEDAMPRAT_STATIC] 	= OBJ_EVENT_PAL_TAG_BEARDEDAMPRAT_SHINY,
	[SPECIES_REDPIKMIN_VETERAN] 	= OBJ_EVENT_PAL_TAG_REDPIKMIN_VETERAN_SHINY,
	[SPECIES_TITANDWEEVIL_ELECTRIC] 	= OBJ_EVENT_PAL_TAG_TITANDWEEVIL_ELECTRIC_SHINY,
	[SPECIES_TITANDWEEVIL_FIRE] 	= OBJ_EVENT_PAL_TAG_TITANDWEEVIL_FIRE_SHINY,
	[SPECIES_TITANDWEEVIL_POISON] 	= OBJ_EVENT_PAL_TAG_TITANDWEEVIL_POISON_SHINY,
	[SPECIES_TITANDWEEVIL_WATER] 	= OBJ_EVENT_PAL_TAG_TITANDWEEVIL_WATER_SHINY,
	[SPECIES_SMOKYPROGG_MASTER] 	= OBJ_EVENT_PAL_TAG_SMOKYPROG_MASTER_SHINY,
	[SPECIES_SPECTRALID_RED] 		= OBJ_EVENT_PAL_TAG_SPECTRALID_RED_SHINY,
	[SPECIES_SPECTRALID_YELLOW] 	= OBJ_EVENT_PAL_TAG_SPECTRALID_YELLOW_SHINY,
	[SPECIES_SPECTRALID_UNMARKED] 	= OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKED_SHINY,
	[SPECIES_SPECTRALID_UNMARKEDRED] 	= OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKEDRED_SHINY,
	[SPECIES_SPECTRALID_UNMARKEDPURPLE] = OBJ_EVENT_PAL_TAG_SPECTRALID_UNMARKEDPURPLE_SHINY,
	[SPECIES_SPECTRALID_ELECTRIC] 	= OBJ_EVENT_PAL_TAG_SPECTRALID_ELECTRIC_SHINY,
	[SPECIES_SPECTRALID_HEY0] 		= OBJ_EVENT_PAL_TAG_SPECTRALID_HEY0_SHINY,
	[SPECIES_SPECTRALID_HEY1] 		= OBJ_EVENT_PAL_TAG_SPECTRALID_HEY1_SHINY,
	[SPECIES_ANCIENTSIREHOUND_ICE] 	= OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_ICE_SHINY,
	[SPECIES_ANCIENTSIREHOUND_ELECTRIC] = OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_ELECTRIC_SHINY,
	[SPECIES_ANCIENTSIREHOUND_FIRE] 	= OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_FIRE_SHINY,
	[SPECIES_ANCIENTSIREHOUND_GLOOM] 	= OBJ_EVENT_PAL_TAG_ANCIENTSIREHOUND_GLOOM_SHINY,
	[SPECIES_KIRBY_FLYING] 		= OBJ_EVENT_PAL_TAG_KIRBY_FLYING_SHINY,
	[SPECIES_KIRBY_GRASS] 		= OBJ_EVENT_PAL_TAG_KIRBY_GRASS_SHINY,
	[SPECIES_KIRBY_BUG] 		= OBJ_EVENT_PAL_TAG_KIRBY_BUG_SHINY,
	[SPECIES_KIRBY_POISON] 		= OBJ_EVENT_PAL_TAG_KIRBY_POISON_SHINY,
	[SPECIES_KIRBY_WATER] 		= OBJ_EVENT_PAL_TAG_KIRBY_WATER_SHINY,
	[SPECIES_KIRBY_ICE] 		= OBJ_EVENT_PAL_TAG_KIRBY_ICE_SHINY,
	[SPECIES_KIRBY_FIRE] 		= OBJ_EVENT_PAL_TAG_KIRBY_FIRE_SHINY,
	[SPECIES_KIRBY_ELECTRIC] 		= OBJ_EVENT_PAL_TAG_KIRBY_ELECTRIC_SHINY,
	[SPECIES_KIRBY_FIGHTING] 		= OBJ_EVENT_PAL_TAG_KIRBY_FIGHTING_SHINY,
	[SPECIES_KIRBY_ROCK] 		= OBJ_EVENT_PAL_TAG_KIRBY_ROCK_SHINY,
	[SPECIES_KIRBY_GROUND] 		= OBJ_EVENT_PAL_TAG_KIRBY_GROUND_SHINY,
	[SPECIES_KIRBY_PSYCHIC] 		= OBJ_EVENT_PAL_TAG_KIRBY_PSYCHIC_SHINY,
	[SPECIES_KIRBY_GHOST] 		= OBJ_EVENT_PAL_TAG_KIRBY_GHOST_SHINY,
	[SPECIES_KIRBY_DRAGON] 		= OBJ_EVENT_PAL_TAG_KIRBY_DRAGON_SHINY,
	[SPECIES_KIRBY_DARK] 		= OBJ_EVENT_PAL_TAG_KIRBY_DARK_SHINY,
	[SPECIES_KIRBY_STEEL] 		= OBJ_EVENT_PAL_TAG_KIRBY_STEEL_SHINY,
	[SPECIES_KIRBY_FAIRY]	 	= OBJ_EVENT_PAL_TAG_KIRBY_FAIRY_SHINY,
	[SPECIES_SOUL_RED] 			= OBJ_EVENT_PAL_TAG_SOUL_RED_SHINY,
	[SPECIES_SOUL_YELLOW] 		= OBJ_EVENT_PAL_TAG_SOUL_YELLOW_SHINY,
	[SPECIES_SOUL_BLUE] 		= OBJ_EVENT_PAL_TAG_SOUL_BLUE_SHINY,
	[SPECIES_SOUL_PURPLE] 		= OBJ_EVENT_PAL_TAG_SOUL_PURPLE_SHINY,
	[SPECIES_SOUL_WHITE] 		= OBJ_EVENT_PAL_TAG_SOUL_WHITE_SHINY,
	[SPECIES_SOUL_ROCK] 		= OBJ_EVENT_PAL_TAG_SOUL_ROCK_SHINY,
	[SPECIES_SOUL_WINGED] 		= OBJ_EVENT_PAL_TAG_SOUL_WINGED_SHINY,
	[SPECIES_SOUL_ICE] 			= OBJ_EVENT_PAL_TAG_SOUL_ICE_SHINY,

	[SPECIES_JUMBOBULBORB_MEGA] 	= OBJ_EVENT_PAL_TAG_JUMBOBULBORB_SHINY,
	[SPECIES_TITANBLOWHOG_MEGA] 	= OBJ_EVENT_PAL_TAG_TITANBLOWHOG_SHINY,
	[SPECIES_MASTERHOP_MEGA] 		= OBJ_EVENT_PAL_TAG_MASTERHOP_SHINY,
	[SPECIES_GLINTBEETLE_MEGA] 		= OBJ_EVENT_PAL_TAG_GLINTBEETLE_SHINY,
	[SPECIES_DIRIGIBUG_MEGA] 		= OBJ_EVENT_PAL_TAG_DIRIGIBUG_SHINY,		//15
	[SPECIES_GIANTBREADBUG_MEGA] 	= OBJ_EVENT_PAL_TAG_GIANTBREADBUG_SHINY,
	[SPECIES_SOVREIGNBULBLAX_MEGA] 	= OBJ_EVENT_PAL_TAG_SOVREIGNBULBLAX_SHINY,
	[SPECIES_DANDELFLY_MEGA] 		= OBJ_EVENT_PAL_TAG_DANDELFLY_SHINY,
	[SPECIES_PILEATEDSNAGRET_MEGA] 	= OBJ_EVENT_PAL_TAG_PILEATEDSNAGRET_SHINY,
	[SPECIES_DESICCATEDSKITTERLEAF_MEGA]= OBJ_EVENT_PAL_TAG_DESICCATEDSKITTERLEAF_SHINY,	//44
	[SPECIES_ADULTBULBMIN_MEGAB] 	= OBJ_EVENT_PAL_TAG_ADULTBULBMIN_SHINY,
	[SPECIES_ADULTBULBMIN_MEGAS] 	= OBJ_EVENT_PAL_TAG_ADULTBULBMIN_SHINY,
	[SPECIES_MANATLEGS_MEGA] 		= OBJ_EVENT_PAL_TAG_MANATLEGS_SHINY,
	[SPECIES_VEHEAMOTHPHOSBAT_MEGA] 	= OBJ_EVENT_PAL_TAG_VEHEAMOTHPHOSBAT_SHINY,	//74
	[SPECIES_PYROCLASTICSLOOCH_MEGA] 	= OBJ_EVENT_PAL_TAG_PYROCLASTICSLOOCH_SHINY,	//84
	[SPECIES_GREATERSPOTTEDJELLYFLOAT_MEGA] = OBJ_EVENT_PAL_TAG_GREATERSPOTTEDJELLYFLOAT_SHINY,	//86
	[SPECIES_SNOWFLAKEFLUTTERTAIL_MEGA] = OBJ_EVENT_PAL_TAG_SNOWFLAKEFLUTTERTAIL_SHINY,	//99
	[SPECIES_BOGSWALLOW_MEGA] 		= OBJ_EVENT_PAL_TAG_BOGSWALLOW_SHINY,		//100
	[SPECIES_PUFFMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_PUFFMIN_SHINY,
	[SPECIES_SCORCHCAKE_MEGA] 		= OBJ_EVENT_PAL_TAG_SCORCHCAKE_SHINY,		//105
	[SPECIES_PUFFSTOOL_MEGA] 		= OBJ_EVENT_PAL_TAG_PUFFSTOOL_SHINY,		//112
	[SPECIES_EMPRESSBULBLAX_MEGA] 	= OBJ_EVENT_PAL_TAG_EMPRESSBULBLAX_SHINY,
	[SPECIES_MUCKERSKATE_MEGA] 		= OBJ_EVENT_PAL_TAG_MUCKERSKATE_SHINY,		//116
	[SPECIES_GROOVYLONGLEGS_MEGA] 	= OBJ_EVENT_PAL_TAG_GROOVYLONGLEGS_SHINY,		//117
	[SPECIES_CRUSTEDRUMPUP_MEGA] 	= OBJ_EVENT_PAL_TAG_CRUSTEDRUMPUP_SHINY,		//118
	[SPECIES_GATTLINGGROINK_MEGA] 	= OBJ_EVENT_PAL_TAG_GATTLINGGROINK_SHINY,		//121
	[SPECIES_ARMOREDMAWDAD_MEGA] 	= OBJ_EVENT_PAL_TAG_ARMOREDMAWDAD_SHINY,
	[SPECIES_OATCHI_MEGA] 		= OBJ_EVENT_PAL_TAG_OATCHI_SHINY,
	[SPECIES_QUAGGLEDMIRECLOPS_MEGA] 	= OBJ_EVENT_PAL_TAG_QUAGGLEDMIRECLOPS_SHINY,
	[SPECIES_WHITEPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_WHITEPIKMIN_SHINY,
	[SPECIES_BLUEPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_BLUEPIKMIN_SHINY,
	[SPECIES_ROCKPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_ROCKPIKMIN_SHINY,
	[SPECIES_YELLOWPIKMIN_MEGA] 	= OBJ_EVENT_PAL_TAG_YELLOWPIKMIN_SHINY,
	[SPECIES_WINGEDPIKMIN_MEGA] 	= OBJ_EVENT_PAL_TAG_WINGEDPIKMIN_SHINY,
	[SPECIES_REDPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_REDPIKMIN_SHINY,
	[SPECIES_PURPLEPIKMIN_MEGA] 	= OBJ_EVENT_PAL_TAG_PURPLEPIKMIN_SHINY,
	[SPECIES_ICEPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_ICEPIKMIN_SHINY,
	[SPECIES_GLOWPIKMIN_MEGA] 		= OBJ_EVENT_PAL_TAG_GLOWPIKMIN_SHINY,
	[SPECIES_MOSS_MEGA] 		= OBJ_EVENT_PAL_TAG_MOSS_SHINY,
	[SPECIES_WATERYBLOWHOG_MEGA] 	= OBJ_EVENT_PAL_TAG_WATERYBLOWHOG_SHINY,		//170
	[SPECIES_OATCHI_MEGAB] 		= OBJ_EVENT_PAL_TAG_OATCHI_SHINY,
	[SPECIES_MOSS_MEGAB] 		= OBJ_EVENT_PAL_TAG_MOSS_SHINY,

	[SPECIES_ICEBLOWNDWEEVIL_F] 	= OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_F_SHINY,
	[SPECIES_ICEBLOWNDWEEVIL_E] 	= OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_E_SHINY,
	[SPECIES_ICEBLOWNDWEEVIL_W] 	= OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_W_SHINY,
	[SPECIES_ICEBLOWNDWEEVIL_P] 	= OBJ_EVENT_PAL_TAG_ICEBLOWNDWEEVIL_P_SHINY,
	[SPECIES_REDBUBBLIMP] 		= OBJ_EVENT_PAL_TAG_REDBUBBLIMP_SHINY,
	[SPECIES_STARNACLE] 		= OBJ_EVENT_PAL_TAG_STARNACLE_SHINY,
	[SPECIES_SHEARFLEA] 		= OBJ_EVENT_PAL_TAG_SHEARFLEA_SHINY,
	[SPECIES_WHISKERPILLAR] 		= OBJ_EVENT_PAL_TAG_WHISKERPILLAR_SHINY,
	[SPECIES_ICYBLOWHOG] 		= OBJ_EVENT_PAL_TAG_ICYBLOWHOG_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM] 		= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM_BULBORB] 	= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_BULBORB_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM_AMPRAT] 	= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_AMPRAT_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM_DANDELFLY] 	= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_DANDELFLY_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM_ARACHNODE] 	= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_ARACHNODE_SHINY,
	[SPECIES_MYSTERIOUSLIFEFORM_BLOWHOG] 	= OBJ_EVENT_PAL_TAG_MYSTERIOUSLIFEFORM_BLOWHOG_SHINY,

	[SPECIES_WATERWRAITH_NOTIRES] = OBJ_EVENT_PAL_TAG_WATERWRAITH_SHINY,
	[SPECIES_WHISKERPILLAR_MEGAB] = OBJ_EVENT_PAL_TAG_WHISKERPILLAR_SHINY,
	[SPECIES_WHISKERPILLAR_MEGAS] = OBJ_EVENT_PAL_TAG_WHISKERPILLAR_SHINY,
	[SPECIES_PETEYPIRANNHA] = OBJ_EVENT_PAL_TAG_PETEYPIRANNHA_SHINY,
	[SPECIES_TOYPIKMIN_RED] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_RED_SHINY,
	[SPECIES_TOYPIKMIN_YELLOW] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_YELLOW_SHINY,
	[SPECIES_TOYPIKMIN_BLUE] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_BLUE_SHINY,
	[SPECIES_PIKI_MALE] = OBJ_EVENT_PAL_TAG_PIKI_MALE_SHINY,
	[SPECIES_PIKI_FEMALE] = OBJ_EVENT_PAL_TAG_PIKI_FEMALE_SHINY,
	[SPECIES_DEMOF] = OBJ_EVENT_PAL_TAG_DEMOF_SHINY,
	[SPECIES_DEMOG] = OBJ_EVENT_PAL_TAG_DEMOG_SHINY,
	[SPECIES_DEMOI] = OBJ_EVENT_PAL_TAG_DEMOI_SHINY,
	[SPECIES_DEMOW] = OBJ_EVENT_PAL_TAG_DEMOW_SHINY,
	[SPECIES_USUALSUSPECT] = OBJ_EVENT_PAL_TAG_USUALSUSPECT_SHINY,
	[SPECIES_METEOR] = OBJ_EVENT_PAL_TAG_METEOR_SHINY,
	[SPECIES_CHERRY] = OBJ_EVENT_PAL_TAG_CHERRY_SHINY,
	[SPECIES_ANTENNABEETLE] = OBJ_EVENT_PAL_TAG_ANTENNABEETLE_SHINY,
	[SPECIES_FIERYYOUNGYELLOWWOLLYHOP] = OBJ_EVENT_PAL_TAG_FIERYYOUNGYELLOWWOLLYHOP_SHINY,
	[SPECIES_HOTELTRANSYLVANIA] = OBJ_EVENT_PAL_TAG_HOTELTRANSYLVANIA_SHINY,
	[SPECIES_CALYREX] = OBJ_EVENT_PAL_TAG_CALYREX_SHINY,
	[SPECIES_HONEYWISP_MEGA] = OBJ_EVENT_PAL_TAG_HONEYWISP_SHINY,
	[SPECIES_FREEZECAKE] = OBJ_EVENT_PAL_TAG_FREEZECAKE_SHINY,
	[SPECIES_SHOCKCAKE] = OBJ_EVENT_PAL_TAG_SHOCKCAKE_SHINY,
	[SPECIES_WIDEMOUTHEDANODEBEETLE] = OBJ_EVENT_PAL_TAG_WIDEMOUTHEDANODEBEETLE_SHINY,
	[SPECIES_DECORATEDCANNONBEETLE] = OBJ_EVENT_PAL_TAG_DECORATEDCANNONBEETLE_SHINY,
	
	[SPECIES_REDPIKMIN_VETERAN_MEGA] = OBJ_EVENT_PAL_TAG_REDPIKMIN_VETERAN_SHINY,
	
	[MURAL_WHISKERPILLAR_MEGAB] = OBJ_EVENT_PAL_TAG_WHISKERPILLAR_SHINY,
	[MURAL_WHISKERPILLAR_MEGAS] = OBJ_EVENT_PAL_TAG_WHISKERPILLAR_SHINY,
	[MURAL_PETEYPIRANNHA] = OBJ_EVENT_PAL_TAG_PETEYPIRANNHA_SHINY,
	[MURAL_TOYPIKMIN_RED] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_RED_SHINY,
	[MURAL_TOYPIKMIN_YELLOW] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_YELLOW_SHINY,
	[MURAL_TOYPIKMIN_BLUE] = OBJ_EVENT_PAL_TAG_TOYPIKMIN_BLUE_SHINY,
	[MURAL_PIKI_MALE] = OBJ_EVENT_PAL_TAG_PIKI_MALE_SHINY,
	[MURAL_PIKI_FEMALE] = OBJ_EVENT_PAL_TAG_PIKI_FEMALE_SHINY,
	[MURAL_DEMOF] = OBJ_EVENT_PAL_TAG_DEMOF_SHINY,
	[MURAL_DEMOG] = OBJ_EVENT_PAL_TAG_DEMOG_SHINY,
	[MURAL_DEMOI] = OBJ_EVENT_PAL_TAG_DEMOI_SHINY,
	[MURAL_DEMOW] = OBJ_EVENT_PAL_TAG_DEMOW_SHINY,
	[MURAL_USUALSUSPECT] = OBJ_EVENT_PAL_TAG_USUALSUSPECT_SHINY,
	[MURAL_METEOR] = OBJ_EVENT_PAL_TAG_METEOR_SHINY,
	[MURAL_CHERRY] = OBJ_EVENT_PAL_TAG_CHERRY_SHINY,
	[MURAL_FIERYYOUNGYELLOWWOLLYHOP] = OBJ_EVENT_PAL_TAG_FIERYYOUNGYELLOWWOLLYHOP_SHINY,
	[MURAL_HOTELTRANSYLVANIA] = OBJ_EVENT_PAL_TAG_HOTELTRANSYLVANIA_SHINY,
	[MURAL_CALYREX] = OBJ_EVENT_PAL_TAG_CALYREX_SHINY,
	[MURAL_HONEYWISP_MEGA] = OBJ_EVENT_PAL_TAG_HONEYWISP_SHINY,

	[SPECIES_SKELEMIN] =    OBJ_EVENT_PAL_TAG_SKELEMIN_SHINY,
	[SPECIES_SKELEMIN_MEGA] =    OBJ_EVENT_PAL_TAG_SKELEMIN_SHINY,
	[SPECIES_MOYAIMIN] =    OBJ_EVENT_PAL_TAG_MOYAIMIN_SHINY,
	[SPECIES_MOYAIMIN_MEGA] =    OBJ_EVENT_PAL_TAG_MOYAIMIN_SHINY,
	[SPECIES_COCKATRICE] =    OBJ_EVENT_PAL_TAG_COCKATRICE_SHINY,
	[SPECIES_BUPBORB] =    OBJ_EVENT_PAL_TAG_BUPBORB_SHINY,
	[SPECIES_DWARFKERMIT] =    OBJ_EVENT_PAL_TAG_DWARFKERMIT_SHINY,
	[SPECIES_BULBLAXLARVA] =    OBJ_EVENT_PAL_TAG_BULBLAXLARVA_SHINY,
	[SPECIES_COALBEETLE] =    OBJ_EVENT_PAL_TAG_COALBEETLE_SHINY,
	[SPECIES_HEAVYCANNONLARVA] =    OBJ_EVENT_PAL_TAG_HEAVYCANNONLARVA_SHINY,
	[SPECIES_CREWMATE] =    OBJ_EVENT_PAL_TAG_CREWMATE_SHINY,
	[SPECIES_IMPOSTER] =    OBJ_EVENT_PAL_TAG_IMPOSTER_SHINY,
	[SPECIES_APACHE] =    OBJ_EVENT_PAL_TAG_APACHE_SHINY,
	[SPECIES_MORSHUBUG] =    OBJ_EVENT_PAL_TAG_MORSHUBUG_SHINY,
	[SPECIES_SKITTERJUANA] =    OBJ_EVENT_PAL_TAG_SKITTERJUANA_SHINY,
	[SPECIES_WAHPOLE] =    OBJ_EVENT_PAL_TAG_WAHPOLE_SHINY,
	[SPECIES_WALUIGIWOG] =    OBJ_EVENT_PAL_TAG_WALUIGIWOG_SHINY,
	[SPECIES_STEPHAN] =    OBJ_EVENT_PAL_TAG_STEPHAN_SHINY,
	[SPECIES_LINKGRET] =    OBJ_EVENT_PAL_TAG_LINKGRET_SHINY,
	[SPECIES_OLIMANATLEGS] =    OBJ_EVENT_PAL_TAG_OLIMANATLEGS_SHINY,
	[SPECIES_BULBEEL] =    OBJ_EVENT_PAL_TAG_BULBEEL_SHINY,
	[SPECIES_IWAGEN] =    OBJ_EVENT_PAL_TAG_IWAGEN_SHINY,
	[SPECIES_128MARIOS] =    OBJ_EVENT_PAL_TAG_128MARIOS_SHINY,
	[SPECIES_FIDDLEHEAD] =    OBJ_EVENT_PAL_TAG_FIDDLEHEAD_SHINY,
	[SPECIES_HORSETAIL] =    OBJ_EVENT_PAL_TAG_HORSETAIL_SHINY,
	[SPECIES_SPOTCAP] =    OBJ_EVENT_PAL_TAG_SPOTCAP_SHINY,
	[SPECIES_KINGCAP] =    OBJ_EVENT_PAL_TAG_KINGCAP_SHINY,
	[SPECIES_BULBIE] =    OBJ_EVENT_PAL_TAG_BULBIE_SHINY,
	[SPECIES_SLUGCAT] =    OBJ_EVENT_PAL_TAG_SLUGCAT_SHINY,
	[SPECIES_PINKELEBIT] =    OBJ_EVENT_PAL_TAG_PINKELEBIT_SHINY,
	[SPECIES_PRIMALASPID] =    OBJ_EVENT_PAL_TAG_PRIMALASPID_SHINY,
	[SPECIES_CHIBIROBO] =    OBJ_EVENT_PAL_TAG_CHIBIROBO_SHINY,
	[SPECIES_PIKACHU] =    OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,

	[MURAL_SKELEMIN] =    OBJ_EVENT_PAL_TAG_SKELEMIN_SHINY,
	[MURAL_SKELEMIN_MEGA] =    OBJ_EVENT_PAL_TAG_SKELEMIN_SHINY,
	[MURAL_MOYAIMIN] =    OBJ_EVENT_PAL_TAG_MOYAIMIN_SHINY,
	[MURAL_MOYAIMIN_MEGA] =    OBJ_EVENT_PAL_TAG_MOYAIMIN_SHINY,
	[MURAL_COCKATRICE] =    OBJ_EVENT_PAL_TAG_COCKATRICE_SHINY,
	[MURAL_BUPBORB] =    OBJ_EVENT_PAL_TAG_BUPBORB_SHINY,
	[MURAL_DWARFKERMIT] =    OBJ_EVENT_PAL_TAG_DWARFKERMIT_SHINY,
	[MURAL_BULBLAXLARVA] =    OBJ_EVENT_PAL_TAG_BULBLAXLARVA_SHINY,
	[MURAL_COALBEETLE] =    OBJ_EVENT_PAL_TAG_COALBEETLE_SHINY,
	[MURAL_HEAVYCANNONLARVA] =    OBJ_EVENT_PAL_TAG_HEAVYCANNONLARVA_SHINY,
	[MURAL_CREWMATE] =    OBJ_EVENT_PAL_TAG_CREWMATE_SHINY,
	[MURAL_IMPOSTER] =    OBJ_EVENT_PAL_TAG_IMPOSTER_SHINY,
	[MURAL_APACHE] =    OBJ_EVENT_PAL_TAG_APACHE_SHINY,
	[MURAL_MORSHUBUG] =    OBJ_EVENT_PAL_TAG_MORSHUBUG_SHINY,
	[MURAL_SKITTERJUANA] =    OBJ_EVENT_PAL_TAG_SKITTERJUANA_SHINY,
	[MURAL_WAHPOLE] =    OBJ_EVENT_PAL_TAG_WAHPOLE_SHINY,
	[MURAL_WALUIGIWOG] =    OBJ_EVENT_PAL_TAG_WALUIGIWOG_SHINY,
	[MURAL_STEPHAN] =    OBJ_EVENT_PAL_TAG_STEPHAN_SHINY,
	[MURAL_LINKGRET] =    OBJ_EVENT_PAL_TAG_LINKGRET_SHINY,
	[MURAL_OLIMANATLEGS] =    OBJ_EVENT_PAL_TAG_OLIMANATLEGS_SHINY,
	[MURAL_BULBEEL] =    OBJ_EVENT_PAL_TAG_BULBEEL_SHINY,
	[MURAL_IWAGEN] =    OBJ_EVENT_PAL_TAG_IWAGEN_SHINY,
	[MURAL_128MARIOS] =    OBJ_EVENT_PAL_TAG_128MARIOS_SHINY,
	[MURAL_FIDDLEHEAD] =    OBJ_EVENT_PAL_TAG_FIDDLEHEAD_SHINY,
	[MURAL_HORSETAIL] =    OBJ_EVENT_PAL_TAG_HORSETAIL_SHINY,
	[MURAL_SPOTCAP] =    OBJ_EVENT_PAL_TAG_SPOTCAP_SHINY,
	[MURAL_KINGCAP] =    OBJ_EVENT_PAL_TAG_KINGCAP_SHINY,
	[MURAL_BULBIE] =    OBJ_EVENT_PAL_TAG_BULBIE_SHINY,
	[MURAL_SLUGCAT] =    OBJ_EVENT_PAL_TAG_SLUGCAT_SHINY,
	[MURAL_PINKELEBIT] =    OBJ_EVENT_PAL_TAG_PINKELEBIT_SHINY,
	[MURAL_PRIMALASPID] =    OBJ_EVENT_PAL_TAG_PRIMALASPID_SHINY,
	[MURAL_CHIBIROBO] =    OBJ_EVENT_PAL_TAG_CHIBIROBO_SHINY,
	[MURAL_PIKACHU] =    OBJ_EVENT_PAL_TAG_PIKACHU_SHINY,
};

void ChangeFollowerPalette(void)
{
    u8 followerId = GetFollowerMapObjId();
    if (followerId >= MAP_OBJECTS_COUNT)
        return;

    struct EventObject* follower = &gEventObjects[followerId];
    if (!follower->active)
        return;

    u8 spriteId = follower->spriteId;
    if (spriteId >= MAX_SPRITES)
        return;

    struct Pokemon* mon = GetFirstValidPartyMon();
    if (mon == NULL)
        return;

    if (!IsMonShiny(mon))
        return;

    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    
    u16 paletteTag = (species < ARRAY_COUNT(sSpeciesToPaletteTag)) ? sSpeciesToPaletteTag[species] : 0x0000;
    if (paletteTag == 0x0000)
        return;

    const struct SpritePalette* paletteEntry = NULL;

    for (size_t tableIndex = 0; tableIndex < ARRAY_COUNT(sObjectEventSpritePalettesTables); tableIndex++)
    {
        const struct SpritePalette* paletteTable = sObjectEventSpritePalettesTables[tableIndex];

        for (int i = 0; paletteTable[i].data != NULL; i++)
        {
            if (paletteTable[i].tag == paletteTag)
            {
                paletteEntry = &paletteTable[i];
                break;
            }
        }

        if (paletteEntry != NULL)
            break;
    }

    if (paletteEntry == NULL)
        return;

    LoadPalette(paletteEntry->data, 0x100 + (16 * gSprites[spriteId].oam.paletteNum), 0x20);
    ApplyGlobalFieldPaletteTint(gSprites[spriteId].oam.paletteNum);
}
